import type { LessonCopyKey } from './lesson.ts';

// The words the figures use (lesson.ts) in Traditional Chinese as written in Taiwan, in the terms
// of the zh-TW dictionary. Not read yet: lesson.ts takes them when LessonLanguage gains zh-TW.

export const LESSON_WORDS_ZH_TW: Record<LessonCopyKey, string> = {
  plate: '圖',
  start: '開始',
  again: '再來一次',
  progress: '第 {n} 題，共 {total} 題',
  found: '已找到 {n} / {total}',
  allFound: '全部找到了，很好。',
  right: '對了：{name}。',
  notIt: '這是 {name}。',
  wrong: '你彈的是 {played}。正確答案是 {answer}，已經在鍵盤上標出來了。',
  done: '完成：{total} 題中有 {right} 題一次就答對。',
  howToPlay: '用 MIDI 鍵盤彈，點螢幕上的琴鍵，或者用電腦鍵盤：A 鍵是 C4，Z 和 X 切換八度。',
  listening: '正在聽：請在鍵盤上彈。',
  ready: '準備好了就點「開始」。',
  lastPlayed: '你彈的是',
  playAny: '隨便彈一個鍵',
  middleC: '中央 C',
  listen: '聽聽看',
  line: '第 {n} 線',
  space: '第 {n} 間',
  next: '下一個：{name}',
  sequenceDone: '彈完了：一共 {total} 個音，途中按錯 {slips} 次。',
  choiceRight: '對了。',
  choiceWrong: '不對，答案是 {answer}。',
  nextQuestion: '下一題',
  stop: '停止',
  tapAlong: '跟著拍子，隨便按一個鍵。',
  early: '早了',
  late: '晚了',
  onTime: '準',
  offBy: '{side} {ms} 毫秒',
  rhythmDone: '{total} 個音裡有 {good} 個在拍子上。{tendency}',
  tendsEarly: '你整體稍微偏早。',
  tendsLate: '你整體稍微偏晚。',
  tendsEven: '很均勻。',
  countIn: '預備拍⋯',
  another: '換一個',
  halfStep: '半音',
  wholeStep: '全音',
  countTrip: '連',
  countLet: '音',
  skip: '跳過',
  fixedTouch:
    '電腦鍵盤、點按或觸控永遠用同一個力度彈，是 127 裡的 96。能感應觸鍵的 MIDI 鍵盤，才能顯示你彈得多重。',
  velocity: '{v} / 127',
  joined: '連上了',
  gap: '斷開 {ms} 毫秒',
  overlap: '重疊 {ms} 毫秒',
  joins: '{joined} 處連上，{gaps} 處斷開，{overlaps} 處重疊。',
  lastJoin: '最後一處：',
  noteProgress: '第 {n} 個音，共 {total} 個',
  keysLane: '琴鍵',
  pedalLane: '踏板',
  soundLane: '聲音',
  gapMark: '斷開',
  blurMark: '混濁',
  chordProgress: '第 {n} 個和弦，共 {total} 個',
  fingersOnly: '延音踏板踩著：聲音還在延續，這裡顯示的是你的手指。',
  playSome: '彈幾個音試試看。',
  chordListening: '正在聽：彈出這個和弦，幾個音一起彈或一個一個彈都可以。',
  chordSoFar: '已經彈了：{notes}。',
  chordWrong: '{name} 不在這個和弦裡。重新來：它是 {answer}，已經在鍵盤上標出來了。',
  chordRight: '對了：{answer}。',
  chordBass: '音都對，但最低的音不對。重新來：{answer}。',
};
