// Generated by scripts/piano/build.ts from the Salamander Grand Piano V3 (retuned SFZ); do not edit.

/** The velocity layers, soft to loud: `id` names the files, `velocity` is what a layer stands for. */
export const PIANO_LAYERS = [
  { id: 'p', velocity: 40 },
  { id: 'mf', velocity: 68 },
  { id: 'f', velocity: 100 },
] as const;

/** The sampled keys, low to high: its MIDI key, the file name's note and the retuning in cents. */
export const PIANO_SAMPLES: readonly { key: number; name: string; tune: number }[] = [
  { key: 21, name: 'A0', tune: 10 },
  { key: 24, name: 'C1', tune: 13 },
  { key: 27, name: 'Ds1', tune: 11 },
  { key: 30, name: 'Fs1', tune: -3 },
  { key: 33, name: 'A1', tune: -9 },
  { key: 36, name: 'C2', tune: -9 },
  { key: 39, name: 'Ds2', tune: -11 },
  { key: 42, name: 'Fs2', tune: -7 },
  { key: 45, name: 'A2', tune: -4 },
  { key: 48, name: 'C3', tune: 0 },
  { key: 51, name: 'Ds3', tune: -6 },
  { key: 54, name: 'Fs3', tune: -3 },
  { key: 57, name: 'A3', tune: -3 },
  { key: 60, name: 'C4', tune: -6 },
  { key: 63, name: 'Ds4', tune: -3 },
  { key: 66, name: 'Fs4', tune: 0 },
  { key: 69, name: 'A4', tune: -4 },
  { key: 72, name: 'C5', tune: -8 },
  { key: 75, name: 'Ds5', tune: -8 },
  { key: 78, name: 'Fs5', tune: -5 },
  { key: 81, name: 'A5', tune: -7 },
  { key: 84, name: 'C6', tune: -8 },
  { key: 87, name: 'Ds6', tune: -12 },
  { key: 90, name: 'Fs6', tune: -13 },
  { key: 93, name: 'A6', tune: -12 },
  { key: 96, name: 'C7', tune: -17 },
  { key: 99, name: 'Ds7', tune: -17 },
  { key: 102, name: 'Fs7', tune: -27 },
  { key: 105, name: 'A7', tune: -38 },
  { key: 108, name: 'C8', tune: -38 },
];
