import { describe, expect, it } from 'vitest';
import part1Json from '../../scripts/scales/hanon/part1/part1.json?raw';
import { HANON_PART_ONE } from './hanonPartOne.ts';
import {
  partOneCorrections,
  partOneData,
  readPartOne,
  renderPartOneModule,
} from './hanonPartOneData.ts';
import { fnv1a } from './pieceRecords.ts';
import { scaleNotes } from './scales.ts';
import { barsOf } from './technique.ts';

const entries = readPartOne(JSON.parse(part1Json) as unknown);

describe('hanonPartOne.ts (generated from part1.json)', () => {
  // The module is generated; rebuilding its data from the transcription must give what is
  // committed, so neither can change without the other (run scripts/scales/hanonPartOne.ts).
  it('holds exactly the data scripts/scales/hanonPartOne.ts builds from part1.json', () => {
    expect(partOneData(entries)).toEqual(HANON_PART_ONE);
  });

  it('renders to a module with the same export', () => {
    const source = renderPartOneModule(partOneData(entries));
    expect(source).toMatch(/^\/\/ Generated by scripts\/scales\/hanonPartOne\.ts/);
    expect(source).toContain('IMSLP #91547');
    expect(source).toContain('export const HANON_PART_ONE');
  });

  /**
   * Locks every note and finger: a deliberate change to the transcription must update this line
   * (and say why in the commit).
   */
  it('is locked by checksum', () => {
    const all = HANON_PART_ONE.map(
      (h) =>
        `${h.number}:${h.beats}:${h.up}:${h.right}|${h.left}|${h.rightFingers}|${h.leftFingers}`,
    ).join(';');
    expect(fnv1a(all)).toBe('acd63e74');
  });

  it('has Nos. 1–20, each two halves and a closing bar, the hands an octave apart', () => {
    expect(HANON_PART_ONE.map((h) => h.number)).toEqual(
      Array.from({ length: 20 }, (_, i) => i + 1),
    );
    for (const h of HANON_PART_ONE) {
      const right = barsOf(h.right);
      const left = barsOf(h.left);
      expect(right.length).toBe(left.length);
      expect(h.beats).toBe(2);
      // Eight sixteenths a bar, in 2/4; the closing bar one note or chord a hand.
      for (const bar of right.slice(0, -1)) expect(bar).toHaveLength(8);
      expect(right.at(-1)).toHaveLength(1);
      const { right: r, left: l } = scaleNotes({
        type: 'hanon',
        tonic: 'C',
        octaves: 2,
        hands: 'both',
        variant: String(h.number),
      });
      const lastIndex = r.at(-1)!.index;
      const rightNotes = r.filter((n) => n.index < lastIndex);
      const leftNotes = l.filter((n) => n.index < lastIndex);
      rightNotes.forEach((n, i) => expect(n.midi - leftNotes[i]!.midi).toBe(12));
    }
  });

  it('takes every digit as printed: the two read doubtfully are 1s, the thumb', () => {
    expect(partOneCorrections(entries)).toEqual([]);
    const nine = HANON_PART_ONE.find((h) => h.number === 9)!;
    expect(nine.rightFingers.split(' | ')[5]![0]).toBe('1');
    const thirteen = HANON_PART_ONE.find((h) => h.number === 13)!;
    expect(thirteen.rightFingers.split(' | ')[5]![1]).toBe('1');
  });
});
