// Generated by scripts/scales/hanonPartOne.ts from scripts/scales/hanon/part1/part1.json.
// Do not edit: change the transcription there and run
//   node --experimental-strip-types scripts/scales/hanonPartOne.ts
//
// Charles-Louis Hanon, The Virtuoso Pianist, Part I, Nos. 1–20, G. Schirmer, New York, n.d.
// [1900], plate 15538, IMSLP #91547: every note as printed, and every fingering digit he prints
// (from the third bar only the fingers each exercise trains; the other notes have none). How it
// was read and checked is in scripts/scales/hanon/README.md.
//
// Each hand is its bars, separated by `|`: the ascending half (`up` bars), the descending half,
// then the closing bar. Notes are sounding pitches (middle C is C4), a chord's keys joined by `+`.
// The fingers are one character per note or chord, `.` where Hanon prints no digit.

export interface HanonPartOne {
  number: number;
  /** Printed page of the G. Schirmer edition. */
  page: number;
  /** Beats to the bar (2: 2/4, as printed). */
  beats: number;
  /** Bars of the ascending half; the descending half follows, then the closing bar. */
  up: number;
  right: string;
  left: string;
  rightFingers: string;
  leftFingers: string;
}

export const HANON_PART_ONE: readonly HanonPartOne[] = [
  {
    number: 1,
    page: 2,
    beats: 2,
    up: 14,
    right:
      'C3 E3 F3 G3 A3 G3 F3 E3 | D3 F3 G3 A3 B3 A3 G3 F3 | E3 G3 A3 B3 C4 B3 A3 G3 | F3 A3 B3 C4 D4 C4 B3 A3 | G3 B3 C4 D4 E4 D4 C4 B3 | A3 C4 D4 E4 F4 E4 D4 C4 | B3 D4 E4 F4 G4 F4 E4 D4 | C4 E4 F4 G4 A4 G4 F4 E4 | D4 F4 G4 A4 B4 A4 G4 F4 | E4 G4 A4 B4 C5 B4 A4 G4 | F4 A4 B4 C5 D5 C5 B4 A4 | G4 B4 C5 D5 E5 D5 C5 B4 | A4 C5 D5 E5 F5 E5 D5 C5 | B4 D5 E5 F5 G5 F5 E5 D5 | G5 E5 D5 C5 B4 C5 D5 E5 | F5 D5 C5 B4 A4 B4 C5 D5 | E5 C5 B4 A4 G4 A4 B4 C5 | D5 B4 A4 G4 F4 G4 A4 B4 | C5 A4 G4 F4 E4 F4 G4 A4 | B4 G4 F4 E4 D4 E4 F4 G4 | A4 F4 E4 D4 C4 D4 E4 F4 | G4 E4 D4 C4 B3 C4 D4 E4 | F4 D4 C4 B3 A3 B3 C4 D4 | E4 C4 B3 A3 G3 A3 B3 C4 | D4 B3 A3 G3 F3 G3 A3 B3 | C4 A3 G3 F3 E3 F3 G3 A3 | B3 G3 F3 E3 D3 E3 F3 G3 | A3 F3 E3 D3 C3 D3 E3 F3 | G3 E3 D3 C3 B2 C3 D3 E3 | C3',
    left: 'C2 E2 F2 G2 A2 G2 F2 E2 | D2 F2 G2 A2 B2 A2 G2 F2 | E2 G2 A2 B2 C3 B2 A2 G2 | F2 A2 B2 C3 D3 C3 B2 A2 | G2 B2 C3 D3 E3 D3 C3 B2 | A2 C3 D3 E3 F3 E3 D3 C3 | B2 D3 E3 F3 G3 F3 E3 D3 | C3 E3 F3 G3 A3 G3 F3 E3 | D3 F3 G3 A3 B3 A3 G3 F3 | E3 G3 A3 B3 C4 B3 A3 G3 | F3 A3 B3 C4 D4 C4 B3 A3 | G3 B3 C4 D4 E4 D4 C4 B3 | A3 C4 D4 E4 F4 E4 D4 C4 | B3 D4 E4 F4 G4 F4 E4 D4 | G4 E4 D4 C4 B3 C4 D4 E4 | F4 D4 C4 B3 A3 B3 C4 D4 | E4 C4 B3 A3 G3 A3 B3 C4 | D4 B3 A3 G3 F3 G3 A3 B3 | C4 A3 G3 F3 E3 F3 G3 A3 | B3 G3 F3 E3 D3 E3 F3 G3 | A3 F3 E3 D3 C3 D3 E3 F3 | G3 E3 D3 C3 B2 C3 D3 E3 | F3 D3 C3 B2 A2 B2 C3 D3 | E3 C3 B2 A2 G2 A2 B2 C3 | D3 B2 A2 G2 F2 G2 A2 B2 | C3 A2 G2 F2 E2 F2 G2 A2 | B2 G2 F2 E2 D2 E2 F2 G2 | A2 F2 E2 D2 C2 D2 E2 F2 | G2 E2 D2 C2 B1 C2 D2 E2 | C2',
    rightFingers:
      '12345... | 12345... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | ........ | ........ | ........ | 54321... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | .',
    leftFingers:
      '54321... | 54321... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | ........ | ........ | ........ | 12345... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | .',
  },
  {
    number: 2,
    page: 3,
    beats: 2,
    up: 14,
    right:
      'C3 E3 A3 G3 F3 G3 F3 E3 | D3 F3 B3 A3 G3 A3 G3 F3 | E3 G3 C4 B3 A3 B3 A3 G3 | F3 A3 D4 C4 B3 C4 B3 A3 | G3 B3 E4 D4 C4 D4 C4 B3 | A3 C4 F4 E4 D4 E4 D4 C4 | B3 D4 G4 F4 E4 F4 E4 D4 | C4 E4 A4 G4 F4 G4 F4 E4 | D4 F4 B4 A4 G4 A4 G4 F4 | E4 G4 C5 B4 A4 B4 A4 G4 | F4 A4 D5 C5 B4 C5 B4 A4 | G4 B4 E5 D5 C5 D5 C5 B4 | A4 C5 F5 E5 D5 E5 D5 C5 | B4 D5 G5 F5 E5 F5 E5 D5 | G5 D5 B4 C5 D5 C5 D5 E5 | F5 C5 A4 B4 C5 B4 C5 D5 | E5 B4 G4 A4 B4 A4 B4 C5 | D5 A4 F4 G4 A4 G4 A4 B4 | C5 G4 E4 F4 G4 F4 G4 A4 | B4 F4 D4 E4 F4 E4 F4 G4 | A4 E4 C4 D4 E4 D4 E4 F4 | G4 D4 B3 C4 D4 C4 D4 E4 | F4 C4 A3 B3 C4 B3 C4 D4 | E4 B3 G3 A3 B3 A3 B3 C4 | D4 A3 F3 G3 A3 G3 A3 B3 | C4 G3 E3 F3 G3 F3 G3 A3 | B3 F3 D3 E3 F3 E3 F3 G3 | A3 E3 C3 D3 E3 D3 E3 F3 | C3',
    left: 'C2 E2 A2 G2 F2 G2 F2 E2 | D2 F2 B2 A2 G2 A2 G2 F2 | E2 G2 C3 B2 A2 B2 A2 G2 | F2 A2 D3 C3 B2 C3 B2 A2 | G2 B2 E3 D3 C3 D3 C3 B2 | A2 C3 F3 E3 D3 E3 D3 C3 | B2 D3 G3 F3 E3 F3 E3 D3 | C3 E3 A3 G3 F3 G3 F3 E3 | D3 F3 B3 A3 G3 A3 G3 F3 | E3 G3 C4 B3 A3 B3 A3 G3 | F3 A3 D4 C4 B3 C4 B3 A3 | G3 B3 E4 D4 C4 D4 C4 B3 | A3 C4 F4 E4 D4 E4 D4 C4 | B3 D4 G4 F4 E4 F4 E4 D4 | G4 D4 B3 C4 D4 C4 D4 E4 | F4 C4 A3 B3 C4 B3 C4 D4 | E4 B3 G3 A3 B3 A3 B3 C4 | D4 A3 F3 G3 A3 G3 A3 B3 | C4 G3 E3 F3 G3 F3 G3 A3 | B3 F3 D3 E3 F3 E3 F3 G3 | A3 E3 C3 D3 E3 D3 E3 F3 | G3 D3 B2 C3 D3 C3 D3 E3 | F3 C3 A2 B2 C3 B2 C3 D3 | E3 B2 G2 A2 B2 A2 B2 C3 | D3 A2 F2 G2 A2 G2 A2 B2 | C3 G2 E2 F2 G2 F2 G2 A2 | B2 F2 D2 E2 F2 E2 F2 G2 | A2 E2 C2 D2 E2 D2 E2 F2 | C2',
    rightFingers:
      '12543432 | 125..... | 125..... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 52123234 | 521..... | 521..... | 521..... | 521..... | 521..... | 521..... | 521..... | 521..... | 52...... | 52...... | 52...... | 52...... | 52...... | .',
    leftFingers:
      '53123234 | 531..... | 531..... | 531..... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 13543432 | 135..... | 135..... | 135..... | 135..... | 135..... | 135..... | 135..... | 135..... | 13...... | 13...... | 13...... | 13...... | 13...... | .',
  },
  {
    number: 3,
    page: 4,
    beats: 2,
    up: 14,
    right:
      'C3 E3 A3 G3 F3 E3 F3 G3 | D3 F3 B3 A3 G3 F3 G3 A3 | E3 G3 C4 B3 A3 G3 A3 B3 | F3 A3 D4 C4 B3 A3 B3 C4 | G3 B3 E4 D4 C4 B3 C4 D4 | A3 C4 F4 E4 D4 C4 D4 E4 | B3 D4 G4 F4 E4 D4 E4 F4 | C4 E4 A4 G4 F4 E4 F4 G4 | D4 F4 B4 A4 G4 F4 G4 A4 | E4 G4 C5 B4 A4 G4 A4 B4 | F4 A4 D5 C5 B4 A4 B4 C5 | G4 B4 E5 D5 C5 B4 C5 D5 | A4 C5 F5 E5 D5 C5 D5 E5 | B4 D5 G5 F5 E5 D5 E5 F5 | G5 D5 B4 C5 D5 E5 D5 C5 | F5 C5 A4 B4 C5 D5 C5 B4 | E5 B4 G4 A4 B4 C5 B4 A4 | D5 A4 F4 G4 A4 B4 A4 G4 | C5 G4 E4 F4 G4 A4 G4 F4 | B4 F4 D4 E4 F4 G4 F4 E4 | A4 E4 C4 D4 E4 F4 E4 D4 | G4 D4 B3 C4 D4 E4 D4 C4 | F4 C4 A3 B3 C4 D4 C4 B3 | E4 B3 G3 A3 B3 C4 B3 A3 | D4 A3 F3 G3 A3 B3 A3 G3 | C4 G3 E3 F3 G3 A3 G3 F3 | B3 F3 D3 E3 F3 G3 F3 E3 | A3 E3 C3 D3 E3 F3 E3 D3 | C3',
    left: 'C2 E2 A2 G2 F2 E2 F2 G2 | D2 F2 B2 A2 G2 F2 G2 A2 | E2 G2 C3 B2 A2 G2 A2 B2 | F2 A2 D3 C3 B2 A2 B2 C3 | G2 B2 E3 D3 C3 B2 C3 D3 | A2 C3 F3 E3 D3 C3 D3 E3 | B2 D3 G3 F3 E3 D3 E3 F3 | C3 E3 A3 G3 F3 E3 F3 G3 | D3 F3 B3 A3 G3 F3 G3 A3 | E3 G3 C4 B3 A3 G3 A3 B3 | F3 A3 D4 C4 B3 A3 B3 C4 | G3 B3 E4 D4 C4 B3 C4 D4 | A3 C4 F4 E4 D4 C4 D4 E4 | B3 D4 G4 F4 E4 D4 E4 F4 | G4 D4 B3 C4 D4 E4 D4 C4 | F4 C4 A3 B3 C4 D4 C4 B3 | E4 B3 G3 A3 B3 C4 B3 A3 | D4 A3 F3 G3 A3 B3 A3 G3 | C4 G3 E3 F3 G3 A3 G3 F3 | B3 F3 D3 E3 F3 G3 F3 E3 | A3 E3 C3 D3 E3 F3 E3 D3 | G3 D3 B2 C3 D3 E3 D3 C3 | F3 C3 A2 B2 C3 D3 C3 B2 | E3 B2 G2 A2 B2 C3 B2 A2 | D3 A2 F2 G2 A2 B2 A2 G2 | C3 G2 E2 F2 G2 A2 G2 F2 | B2 F2 D2 E2 F2 G2 F2 E2 | A2 E2 C2 D2 E2 F2 E2 D2 | C2',
    rightFingers:
      '12543234 | 125432.. | 125..... | 125..... | 125..... | 125..... | 125..... | 125..... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 52123432 | 521..... | 521..... | 521..... | 521..... | 521..... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | .',
    leftFingers:
      '53123432 | 531234.. | 531..... | 531..... | 531..... | 531..... | 531..... | 531..... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 13543234 | 135..... | 135..... | 135..... | 135..... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | .',
  },
  {
    number: 4,
    page: 5,
    beats: 2,
    up: 14,
    right:
      'C3 D3 C3 E3 A3 G3 F3 E3 | D3 E3 D3 F3 B3 A3 G3 F3 | E3 F3 E3 G3 C4 B3 A3 G3 | F3 G3 F3 A3 D4 C4 B3 A3 | G3 A3 G3 B3 E4 D4 C4 B3 | A3 B3 A3 C4 F4 E4 D4 C4 | B3 C4 B3 D4 G4 F4 E4 D4 | C4 D4 C4 E4 A4 G4 F4 E4 | D4 E4 D4 F4 B4 A4 G4 F4 | E4 F4 E4 G4 C5 B4 A4 G4 | F4 G4 F4 A4 D5 C5 B4 A4 | G4 A4 G4 B4 E5 D5 C5 B4 | A4 B4 A4 C5 F5 E5 D5 C5 | B4 C5 B4 D5 G5 F5 E5 D5 | G5 F5 G5 D5 B4 C5 D5 E5 | F5 E5 F5 C5 A4 B4 C5 D5 | E5 D5 E5 B4 G4 A4 B4 C5 | D5 C5 D5 A4 F4 G4 A4 B4 | C5 B4 C5 G4 E4 F4 G4 A4 | B4 A4 B4 F4 D4 E4 F4 G4 | A4 G4 A4 E4 C4 D4 E4 F4 | G4 F4 G4 D4 B3 C4 D4 E4 | F4 E4 F4 C4 A3 B3 C4 D4 | E4 D4 E4 B3 G3 A3 B3 C4 | D4 C4 D4 A3 F3 G3 A3 B3 | C4 B3 C4 G3 E3 F3 G3 A3 | B3 A3 B3 F3 D3 E3 F3 G3 | A3 G3 A3 E3 C3 D3 E3 F3 | C3',
    left: 'C2 D2 C2 E2 A2 G2 F2 E2 | D2 E2 D2 F2 B2 A2 G2 F2 | E2 F2 E2 G2 C3 B2 A2 G2 | F2 G2 F2 A2 D3 C3 B2 A2 | G2 A2 G2 B2 E3 D3 C3 B2 | A2 B2 A2 C3 F3 E3 D3 C3 | B2 C3 B2 D3 G3 F3 E3 D3 | C3 D3 C3 E3 A3 G3 F3 E3 | D3 E3 D3 F3 B3 A3 G3 F3 | E3 F3 E3 G3 C4 B3 A3 G3 | F3 G3 F3 A3 D4 C4 B3 A3 | G3 A3 G3 B3 E4 D4 C4 B3 | A3 B3 A3 C4 F4 E4 D4 C4 | B3 C4 B3 D4 G4 F4 E4 D4 | G4 F4 G4 D4 B3 C4 D4 E4 | F4 E4 F4 C4 A3 B3 C4 D4 | E4 D4 E4 B3 G3 A3 B3 C4 | D4 C4 D4 A3 F3 G3 A3 B3 | C4 B3 C4 G3 E3 F3 G3 A3 | B3 A3 B3 F3 D3 E3 F3 G3 | A3 G3 A3 E3 C3 D3 E3 F3 | G3 F3 G3 D3 B2 C3 D3 E3 | F3 E3 F3 C3 A2 B2 C3 D3 | E3 D3 E3 B2 G2 A2 B2 C3 | D3 C3 D3 A2 F2 G2 A2 B2 | C3 B2 C3 G2 E2 F2 G2 A2 | B2 A2 B2 F2 D2 E2 F2 G2 | A2 G2 A2 E2 C2 D2 E2 F2 | C2',
    rightFingers:
      '12125... | 12.25... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 54521... | 54521... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | .',
    leftFingers:
      '54531... | 54531... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 12135... | 12135... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | .',
  },
  {
    number: 5,
    page: 6,
    beats: 2,
    up: 14,
    right:
      'C3 A3 G3 A3 F3 G3 E3 F3 | D3 B3 A3 B3 G3 A3 F3 G3 | E3 C4 B3 C4 A3 B3 G3 A3 | F3 D4 C4 D4 B3 C4 A3 B3 | G3 E4 D4 E4 C4 D4 B3 C4 | A3 F4 E4 F4 D4 E4 C4 D4 | B3 G4 F4 G4 E4 F4 D4 E4 | C4 A4 G4 A4 F4 G4 E4 F4 | D4 B4 A4 B4 G4 A4 F4 G4 | E4 C5 B4 C5 A4 B4 G4 A4 | F4 D5 C5 D5 B4 C5 A4 B4 | G4 E5 D5 E5 C5 D5 B4 C5 | A4 F5 E5 F5 D5 E5 C5 D5 | B4 G5 F5 G5 E5 F5 D5 E5 | C5 D5 C5 E5 D5 F5 E5 G5 | B4 C5 B4 D5 C5 E5 D5 F5 | A4 B4 A4 C5 B4 D5 C5 E5 | G4 A4 G4 B4 A4 C5 B4 D5 | F4 G4 F4 A4 G4 B4 A4 C5 | E4 F4 E4 G4 F4 A4 G4 B4 | D4 E4 D4 F4 E4 G4 F4 A4 | C4 D4 C4 E4 D4 F4 E4 G4 | B3 C4 B3 D4 C4 E4 D4 F4 | A3 B3 A3 C4 B3 D4 C4 E4 | G3 A3 G3 B3 A3 C4 B3 D4 | F3 G3 F3 A3 G3 B3 A3 C4 | E3 F3 E3 G3 F3 A3 G3 B3 | D3 E3 D3 F3 E3 G3 F3 A3 | C3',
    left: 'C2 A2 G2 A2 F2 G2 E2 F2 | D2 B2 A2 B2 G2 A2 F2 G2 | E2 C3 B2 C3 A2 B2 G2 A2 | F2 D3 C3 D3 B2 C3 A2 B2 | G2 E3 D3 E3 C3 D3 B2 C3 | A2 F3 E3 F3 D3 E3 C3 D3 | B2 G3 F3 G3 E3 F3 D3 E3 | C3 A3 G3 A3 F3 G3 E3 F3 | D3 B3 A3 B3 G3 A3 F3 G3 | E3 C4 B3 C4 A3 B3 G3 A3 | F3 D4 C4 D4 B3 C4 A3 B3 | G3 E4 D4 E4 C4 D4 B3 C4 | A3 F4 E4 F4 D4 E4 C4 D4 | B3 G4 F4 G4 E4 F4 D4 E4 | C4 D4 C4 E4 D4 F4 E4 G4 | B3 C4 B3 D4 C4 E4 D4 F4 | A3 B3 A3 C4 B3 D4 C4 E4 | G3 A3 G3 B3 A3 C4 B3 D4 | F3 G3 F3 A3 G3 B3 A3 C4 | E3 F3 E3 G3 F3 A3 G3 B3 | D3 E3 D3 F3 E3 G3 F3 A3 | C3 D3 C3 E3 D3 F3 E3 G3 | B2 C3 B2 D3 C3 E3 D3 F3 | A2 B2 A2 C3 B2 D3 C3 E3 | G2 A2 G2 B2 A2 C3 B2 D3 | F2 G2 F2 A2 G2 B2 A2 C3 | E2 F2 E2 G2 F2 A2 G2 B2 | D2 E2 D2 F2 E2 G2 F2 A2 | C2',
    rightFingers:
      '15453423 | 15453423 | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 12132435 | 12132435 | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | .',
    leftFingers:
      '51213243 | 51213243 | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 54534231 | 54534231 | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | .',
  },
  {
    number: 6,
    page: 7,
    beats: 2,
    up: 14,
    right:
      'C3 A3 G3 A3 F3 A3 E3 A3 | D3 B3 A3 B3 G3 B3 F3 B3 | E3 C4 B3 C4 A3 C4 G3 C4 | F3 D4 C4 D4 B3 D4 A3 D4 | G3 E4 D4 E4 C4 E4 B3 E4 | A3 F4 E4 F4 D4 F4 C4 F4 | B3 G4 F4 G4 E4 G4 D4 G4 | C4 A4 G4 A4 F4 A4 E4 A4 | D4 B4 A4 B4 G4 B4 F4 B4 | E4 C5 B4 C5 A4 C5 G4 C5 | F4 D5 C5 D5 B4 D5 A4 D5 | G4 E5 D5 E5 C5 E5 B4 E5 | A4 F5 E5 F5 D5 F5 C5 F5 | B4 G5 F5 G5 E5 G5 D5 C5 | G5 B4 C5 B4 D5 B4 E5 B4 | F5 A4 B4 A4 C5 A4 D5 A4 | E5 G4 A4 G4 B4 G4 C5 G4 | D5 F4 G4 F4 A4 F4 B4 F4 | C5 E4 F4 E4 G4 E4 A4 E4 | B4 D4 E4 D4 F4 D4 G4 D4 | A4 C4 D4 C4 E4 C4 F4 C4 | G4 B3 C4 B3 D4 B3 E4 B3 | F4 A3 B3 A3 C4 A3 D4 A3 | E4 G3 A3 G3 B3 G3 C4 G3 | D4 F3 G3 F3 A3 F3 B3 F3 | C4 E3 F3 E3 G3 E3 A3 E3 | B3 D3 E3 D3 F3 D3 G3 D3 | A3 C3 D3 C3 E3 C3 F3 E3 | C3',
    left: 'C2 A2 G2 A2 F2 A2 E2 A2 | D2 B2 A2 B2 G2 B2 F2 B2 | E2 C3 B2 C3 A2 C3 G2 C3 | F2 D3 C3 D3 B2 D3 A2 D3 | G2 E3 D3 E3 C3 E3 B2 E3 | A2 F3 E3 F3 D3 F3 C3 F3 | B2 G3 F3 G3 E3 G3 D3 G3 | C3 A3 G3 A3 F3 A3 E3 A3 | D3 B3 A3 B3 G3 B3 F3 B3 | E3 C4 B3 C4 A3 C4 G3 C4 | F3 D4 C4 D4 B3 D4 A3 D4 | G3 E4 D4 E4 C4 E4 B3 E4 | A3 F4 E4 F4 D4 F4 C4 F4 | B3 G4 F4 G4 E4 G4 D4 C4 | G4 B3 C4 B3 D4 B3 E4 B3 | F4 A3 B3 A3 C4 A3 D4 A3 | E4 G3 A3 G3 B3 G3 C4 G3 | D4 F3 G3 F3 A3 F3 B3 F3 | C4 E3 F3 E3 G3 E3 A3 E3 | B3 D3 E3 D3 F3 D3 G3 D3 | A3 C3 D3 C3 E3 C3 F3 C3 | G3 B2 C3 B2 D3 B2 E3 B2 | F3 A2 B2 A2 C3 A2 D3 A2 | E3 G2 A2 G2 B2 G2 C3 G2 | D3 F2 G2 F2 A2 F2 B2 F2 | C3 E2 F2 E2 G2 E2 A2 E2 | B2 D2 E2 D2 F2 D2 G2 D2 | A2 C2 D2 C2 E2 C2 F2 E2 | C2',
    rightFingers:
      '15453525 | 15453525 | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 51213141 | 51213141 | 51...... | .1...... | .1...... | .1...... | .1...... | .1...... | .1...... | .1...... | .1...... | .1...... | .1...... | .1...... | .',
    leftFingers:
      '51213141 | 51213141 | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 15453525 | 15453525 | 15...... | .5...... | .5...... | .5...... | .5...... | .5...... | .5...... | .5...... | .5...... | .5...... | .5...... | .5...... | .',
  },
  {
    number: 7,
    page: 8,
    beats: 2,
    up: 14,
    right:
      'C3 E3 D3 F3 E3 G3 F3 E3 | D3 F3 E3 G3 F3 A3 G3 F3 | E3 G3 F3 A3 G3 B3 A3 G3 | F3 A3 G3 B3 A3 C4 B3 A3 | G3 B3 A3 C4 B3 D4 C4 B3 | A3 C4 B3 D4 C4 E4 D4 C4 | B3 D4 C4 E4 D4 F4 E4 D4 | C4 E4 D4 F4 E4 G4 F4 E4 | D4 F4 E4 G4 F4 A4 G4 F4 | E4 G4 F4 A4 G4 B4 A4 G4 | F4 A4 G4 B4 A4 C5 B4 A4 | G4 B4 A4 C5 B4 D5 C5 B4 | A4 C5 B4 D5 C5 E5 D5 C5 | B4 D5 C5 E5 D5 F5 E5 D5 | G5 E5 F5 D5 E5 C5 D5 E5 | F5 D5 E5 C5 D5 B4 C5 D5 | E5 C5 D5 B4 C5 A4 B4 C5 | D5 B4 C5 A4 B4 G4 A4 B4 | C5 A4 B4 G4 A4 F4 G4 A4 | B4 G4 A4 F4 G4 E4 F4 G4 | A4 F4 G4 E4 F4 D4 E4 F4 | G4 E4 F4 D4 E4 C4 D4 E4 | F4 D4 E4 C4 D4 B3 C4 D4 | E4 C4 D4 B3 C4 A3 B3 C4 | D4 B3 C4 A3 B3 G3 A3 B3 | C4 A3 B3 G3 A3 F3 G3 A3 | B3 G3 A3 F3 G3 E3 F3 G3 | A3 F3 G3 E3 F3 D3 E3 F3 | C3',
    left: 'C2 E2 D2 F2 E2 G2 F2 E2 | D2 F2 E2 G2 F2 A2 G2 F2 | E2 G2 F2 A2 G2 B2 A2 G2 | F2 A2 G2 B2 A2 C3 B2 A2 | G2 B2 A2 C3 B2 D3 C3 B2 | A2 C3 B2 D3 C3 E3 D3 C3 | B2 D3 C3 E3 D3 F3 E3 D3 | C3 E3 D3 F3 E3 G3 F3 E3 | D3 F3 E3 G3 F3 A3 G3 F3 | E3 G3 F3 A3 G3 B3 A3 G3 | F3 A3 G3 B3 A3 C4 B3 A3 | G3 B3 A3 C4 B3 D4 C4 B3 | A3 C4 B3 D4 C4 E4 D4 C4 | B3 D4 C4 E4 D4 F4 E4 D4 | G4 E4 F4 D4 E4 C4 D4 E4 | F4 D4 E4 C4 D4 B3 C4 D4 | E4 C4 D4 B3 C4 A3 B3 C4 | D4 B3 C4 A3 B3 G3 A3 B3 | C4 A3 B3 G3 A3 F3 G3 A3 | B3 G3 A3 F3 G3 E3 F3 G3 | A3 F3 G3 E3 F3 D3 E3 F3 | G3 E3 F3 D3 E3 C3 D3 E3 | F3 D3 E3 C3 D3 B2 C3 D3 | E3 C3 D3 B2 C3 A2 B2 C3 | D3 B2 C3 A2 B2 G2 A2 B2 | C3 A2 B2 G2 A2 F2 G2 A2 | B2 G2 A2 F2 G2 E2 F2 G2 | A2 F2 G2 E2 F2 D2 E2 F2 | C2',
    rightFingers:
      '13243543 | 13243543 | 1.....4. | 1.....4. | 1.....4. | 1.....4. | 1.....4. | 1.....43 | 1.....43 | 1.....4. | 1.....4. | 1.....4. | 1.....4. | 1.....3. | 53423134 | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | .',
    leftFingers:
      '53423134 | 53423134 | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....34 | 5.....34 | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 5.....3. | 13243543 | 1....54. | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1.....3. | .',
  },
  {
    number: 8,
    page: 9,
    beats: 2,
    up: 14,
    right:
      'C3 E3 G3 A3 F3 G3 E3 F3 | D3 F3 A3 B3 G3 A3 F3 G3 | E3 G3 B3 C4 A3 B3 G3 A3 | F3 A3 C4 D4 B3 C4 A3 B3 | G3 B3 D4 E4 C4 D4 B3 C4 | A3 C4 E4 F4 D4 E4 C4 D4 | B3 D4 F4 G4 E4 F4 D4 E4 | C4 E4 G4 A4 F4 G4 E4 F4 | D4 F4 A4 B4 G4 A4 F4 G4 | E4 G4 B4 C5 A4 B4 G4 A4 | F4 A4 C5 D5 B4 C5 A4 B4 | G4 B4 D5 E5 C5 D5 B4 C5 | A4 C5 E5 F5 D5 E5 C5 D5 | B4 D5 F5 G5 E5 F5 D5 E5 | G5 E5 C5 B4 D5 C5 E5 D5 | F5 D5 B4 A4 C5 B4 D5 C5 | E5 C5 A4 G4 B4 A4 C5 B4 | D5 B4 G4 F4 A4 G4 B4 A4 | C5 A4 F4 E4 G4 F4 A4 G4 | B4 G4 E4 D4 F4 E4 G4 F4 | A4 F4 D4 C4 E4 D4 F4 E4 | G4 E4 C4 B3 D4 C4 E4 D4 | F4 D4 B3 A3 C4 B3 D4 C4 | E4 C4 A3 G3 B3 A3 C4 B3 | D4 B3 G3 F3 A3 G3 B3 A3 | C4 A3 F3 E3 G3 F3 A3 G3 | B3 G3 E3 D3 F3 E3 G3 F3 | A3 F3 D3 C3 E3 D3 F3 E3 | C3',
    left: 'C2 E2 G2 A2 F2 G2 E2 F2 | D2 F2 A2 B2 G2 A2 F2 G2 | E2 G2 B2 C3 A2 B2 G2 A2 | F2 A2 C3 D3 B2 C3 A2 B2 | G2 B2 D3 E3 C3 D3 B2 C3 | A2 C3 E3 F3 D3 E3 C3 D3 | B2 D3 F3 G3 E3 F3 D3 E3 | C3 E3 G3 A3 F3 G3 E3 F3 | D3 F3 A3 B3 G3 A3 F3 G3 | E3 G3 B3 C4 A3 B3 G3 A3 | F3 A3 C4 D4 B3 C4 A3 B3 | G3 B3 D4 E4 C4 D4 B3 C4 | A3 C4 E4 F4 D4 E4 C4 D4 | B3 D4 F4 G4 E4 F4 D4 E4 | G4 E4 C4 B3 D4 C4 E4 D4 | F4 D4 B3 A3 C4 B3 D4 C4 | E4 C4 A3 G3 B3 A3 C4 B3 | D4 B3 G3 F3 A3 G3 B3 A3 | C4 A3 F3 E3 G3 F3 A3 G3 | B3 G3 E3 D3 F3 E3 G3 F3 | A3 F3 D3 C3 E3 D3 F3 E3 | G3 E3 C3 B2 D3 C3 E3 D3 | F3 D3 B2 A2 C3 B2 D3 C3 | E3 C3 A2 G2 B2 A2 C3 B2 | D3 B2 G2 F2 A2 G2 B2 A2 | C3 A2 F2 E2 G2 F2 A2 G2 | B2 G2 E2 D2 F2 E2 G2 F2 | A2 F2 D2 C2 E2 D2 F2 E2 | C2',
    rightFingers:
      '12453423 | 12453... | 124..... | 124..... | 124..... | 124..... | 124..... | 124..... | 124..... | 124..... | 1....... | 1....... | 1....... | 1....... | 54213243 | 54213243 | 5421.... | 5421.... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | 5....... | .',
    leftFingers:
      '54213243 | 54213... | 542..... | 542..... | 542..... | 542..... | 542..... | 542..... | 542..... | 542..... | 5....... | 5....... | 5....... | 5....... | 12453423 | 12453423 | 1245.... | 1245.... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | 1....... | ........ | .',
  },
  {
    number: 9,
    page: 10,
    beats: 2,
    up: 14,
    right:
      'C3 E3 F3 E3 G3 F3 A3 G3 | D3 F3 G3 F3 A3 G3 B3 A3 | E3 G3 A3 G3 B3 A3 C4 B3 | F3 A3 B3 A3 C4 B3 D4 C4 | G3 B3 C4 B3 D4 C4 E4 D4 | A3 C4 D4 C4 E4 D4 F4 E4 | B3 D4 E4 D4 F4 E4 G4 F4 | C4 E4 F4 E4 G4 F4 A4 G4 | D4 F4 G4 F4 A4 G4 B4 A4 | E4 G4 A4 G4 B4 A4 C5 B4 | F4 A4 B4 A4 C5 B4 D5 C5 | G4 B4 C5 B4 D5 C5 E5 D5 | A4 C5 D5 C5 E5 D5 F5 E5 | B4 D5 E5 D5 F5 E5 G5 F5 | G5 E5 D5 E5 C5 D5 B4 C5 | F5 D5 C5 D5 B4 C5 A4 B4 | E5 C5 B4 C5 A4 B4 G4 A4 | D5 B4 A4 B4 G4 A4 F4 G4 | C5 A4 G4 A4 F4 G4 E4 F4 | B4 G4 F4 G4 E4 F4 D4 E4 | A4 F4 E4 F4 D4 E4 C4 D4 | G4 E4 D4 E4 C4 D4 B3 C4 | F4 D4 C4 D4 B3 C4 A3 B3 | E4 C4 B3 C4 A3 B3 G3 A3 | D4 B3 A3 B3 G3 A3 F3 G3 | C4 A3 G3 A3 F3 G3 E3 F3 | B3 G3 F3 G3 E3 F3 D3 E3 | A3 F3 E3 F3 D3 E3 D3 E3 | C3',
    left: 'C2 E2 F2 E2 G2 F2 A2 G2 | D2 F2 G2 F2 A2 G2 B2 A2 | E2 G2 A2 G2 B2 A2 C3 B2 | F2 A2 B2 A2 C3 B2 D3 C3 | G2 B2 C3 B2 D3 C3 E3 D3 | A2 C3 D3 C3 E3 D3 F3 E3 | B2 D3 E3 D3 F3 E3 G3 F3 | C3 E3 F3 E3 G3 F3 A3 G3 | D3 F3 G3 F3 A3 G3 B3 A3 | E3 G3 A3 G3 B3 A3 C4 B3 | F3 A3 B3 A3 C4 B3 D4 C4 | G3 B3 C4 B3 D4 C4 E4 D4 | A3 C4 D4 C4 E4 D4 F4 E4 | B3 D4 E4 D4 F4 E4 G4 F4 | G4 E4 D4 E4 C4 D4 B3 C4 | F4 D4 C4 D4 B3 C4 A3 B3 | E4 C4 B3 C4 A3 B3 G3 A3 | D4 B3 A3 B3 G3 A3 F3 G3 | C4 A3 G3 A3 F3 G3 E3 F3 | B3 G3 F3 G3 E3 F3 D3 E3 | A3 F3 E3 F3 D3 E3 C3 D3 | G3 E3 D3 E3 C3 D3 B2 C3 | F3 D3 C3 D3 B2 C3 A2 B2 | E3 C3 B2 C3 A2 B2 G2 A2 | D3 B2 A2 B2 G2 A2 F2 G2 | C3 A2 G2 A2 F2 G2 E2 F2 | B2 G2 F2 G2 E2 F2 D2 E2 | A2 F2 E2 F2 D2 E2 D2 E2 | C2',
    rightFingers:
      '12324354 | 12324354 | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 54342312 | 54342312 | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | .',
    leftFingers:
      '54342312 | 54342312 | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 54...... | 12324354 | 12324354 | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | .',
  },
  {
    number: 10,
    page: 11,
    beats: 2,
    up: 14,
    right:
      'C3 A3 G3 F3 E3 F3 E3 F3 | D3 B3 A3 G3 F3 G3 F3 G3 | E3 C4 B3 A3 G3 A3 G3 A3 | F3 D4 C4 B3 A3 B3 A3 B3 | G3 E4 D4 C4 B3 C4 B3 C4 | A3 F4 E4 D4 C4 D4 C4 D4 | B3 G4 F4 E4 D4 E4 D4 E4 | C4 A4 G4 F4 E4 F4 E4 F4 | D4 B4 A4 G4 F4 G4 F4 G4 | E4 C5 B4 A4 G4 A4 G4 A4 | F4 D5 C5 B4 A4 B4 A4 B4 | G4 E5 D5 C5 B4 C5 B4 C5 | A4 F5 E5 D5 C5 D5 C5 D5 | B4 G5 F5 E5 D5 E5 D5 E5 | G5 B4 C5 D5 E5 D5 E5 D5 | F5 A4 B4 C5 D5 C5 D5 C5 | E5 G4 A4 B4 C5 B4 C5 B4 | D5 F4 G4 A4 B4 A4 B4 A4 | C5 E4 F4 G4 A4 G4 A4 G4 | B4 D4 E4 F4 G4 F4 G4 F4 | A4 C4 D4 E4 F4 E4 F4 E4 | G4 B3 C4 D4 E4 D4 E4 D4 | F4 A3 B3 C4 D4 C4 D4 C4 | E4 G3 A3 B3 C4 B3 C4 B3 | D4 F3 G3 A3 B3 A3 B3 A3 | C4 E3 F3 G3 A3 G3 A3 G3 | B3 D3 E3 F3 G3 F3 G3 F3 | A3 C3 D3 E3 F3 E3 F3 E3 | C3',
    left: 'C2 A2 G2 F2 E2 F2 E2 F2 | D2 B2 A2 G2 F2 G2 F2 G2 | E2 C3 B2 A2 G2 A2 G2 A2 | F2 D3 C3 B2 A2 B2 A2 B2 | G2 E3 D3 C3 B2 C3 B2 C3 | A2 F3 E3 D3 C3 D3 C3 D3 | B2 G3 F3 E3 D3 E3 D3 E3 | C3 A3 G3 F3 E3 F3 E3 F3 | D3 B3 A3 G3 F3 G3 F3 G3 | E3 C4 B3 A3 G3 A3 G3 A3 | F3 D4 C4 B3 A3 B3 A3 B3 | G3 E4 D4 C4 B3 C4 B3 C4 | A3 F4 E4 D4 C4 D4 C4 D4 | B3 G4 F4 E4 D4 E4 D4 E4 | G4 B3 C4 D4 E4 D4 E4 D4 | F4 A3 B3 C4 D4 C4 D4 C4 | E4 G3 A3 B3 C4 B3 C4 B3 | D4 F3 G3 A3 B3 A3 B3 A3 | C4 E3 F3 G3 A3 G3 A3 G3 | B3 D3 E3 F3 G3 F3 G3 F3 | A3 C3 D3 E3 F3 E3 F3 E3 | G3 B2 C3 D3 E3 D3 E3 D3 | F3 A2 B2 C3 D3 C3 D3 C3 | E3 G2 A2 B2 C3 B2 C3 B2 | D3 F2 G2 A2 B2 A2 B2 A2 | C3 E2 F2 G2 A2 G2 A2 G2 | B2 D2 E2 F2 G2 F2 G2 F2 | A2 C2 D2 E2 F2 E2 F2 E2 | C2',
    rightFingers:
      '15432323 | 15432323 | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | .',
    leftFingers:
      '51234343 | 51234343 | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | .',
  },
  {
    number: 11,
    page: 12,
    beats: 2,
    up: 14,
    right:
      'C3 E3 A3 G3 A3 G3 F3 G3 | D3 F3 B3 A3 B3 A3 G3 A3 | E3 G3 C4 B3 C4 B3 A3 B3 | F3 A3 D4 C4 D4 C4 B3 C4 | G3 B3 E4 D4 E4 D4 C4 D4 | A3 C4 F4 E4 F4 E4 D4 E4 | B3 D4 G4 F4 G4 F4 E4 F4 | C4 E4 A4 G4 A4 G4 F4 G4 | D4 F4 B4 A4 B4 A4 G4 A4 | E4 G4 C5 B4 C5 B4 A4 B4 | F4 A4 D5 C5 D5 C5 B4 C5 | G4 B4 E5 D5 E5 D5 C5 D5 | A4 C5 F5 E5 F5 E5 D5 E5 | B4 D5 G5 F5 G5 F5 E5 F5 | G5 D5 B4 C5 B4 C5 D5 C5 | F5 C5 A4 B4 A4 B4 C5 B4 | E5 B4 G4 A4 G4 A4 B4 A4 | D5 A4 F4 G4 F4 G4 A4 G4 | C5 G4 E4 F4 E4 F4 G4 F4 | B4 F4 D4 E4 D4 E4 F4 E4 | A4 E4 C4 D4 C4 D4 E4 D4 | G4 D4 B3 C4 B3 C4 D4 C4 | F4 C4 A3 B3 A3 B3 C4 B3 | E4 B3 G3 A3 G3 A3 B3 A3 | D4 A3 F3 G3 F3 G3 A3 G3 | C4 G3 E3 F3 E3 F3 G3 F3 | B3 F3 D3 E3 D3 E3 F3 E3 | A3 E3 C3 D3 C3 D3 E3 D3 | C3',
    left: 'C2 E2 A2 G2 A2 G2 F2 G2 | D2 F2 B2 A2 B2 A2 G2 A2 | E2 G2 C3 B2 C3 B2 A2 B2 | F2 A2 D3 C3 D3 C3 B2 C3 | G2 B2 E3 D3 E3 D3 C3 D3 | A2 C3 F3 E3 F3 E3 D3 E3 | B2 D3 G3 F3 G3 F3 E3 F3 | C3 E3 A3 G3 A3 G3 F3 G3 | D3 F3 B3 A3 B3 A3 G3 A3 | E3 G3 C4 B3 C4 B3 A3 B3 | F3 A3 D4 C4 D4 C4 B3 C4 | G3 B3 E4 D4 E4 D4 C4 D4 | A3 C4 F4 E4 F4 E4 D4 E4 | B3 D4 G4 F4 G4 F4 E4 F4 | G4 D4 B3 C4 B3 C4 D4 C4 | F4 C4 A3 B3 A3 B3 C4 B3 | E4 B3 G3 A3 G3 A3 B3 A3 | D4 A3 F3 G3 F3 G3 A3 G3 | C4 G3 E3 F3 E3 F3 G3 F3 | B3 F3 D3 E3 D3 E3 F3 E3 | A3 E3 C3 D3 C3 D3 E3 D3 | G3 D3 B2 C3 B2 C3 D3 C3 | F3 C3 A2 B2 A2 B2 C3 B2 | E3 B2 G2 A2 G2 A2 B2 A2 | D3 A2 F2 G2 F2 G2 A2 G2 | C3 G2 E2 F2 E2 F2 G2 F2 | B2 F2 D2 E2 D2 E2 F2 E2 | A2 E2 C2 D2 C2 D2 E2 D2 | C2',
    rightFingers:
      '12545434 | 125..... | 125..... | 125..... | 125..... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 12...... | 52121232 | 521..... | 521..... | 521..... | 521..... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | .',
    leftFingers:
      '53121232 | 531..... | 531..... | 531..... | 531..... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 53...... | 13545434 | 135..... | 135..... | 135..... | 135..... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | .',
  },
  {
    number: 12,
    page: 13,
    beats: 2,
    up: 14,
    right:
      'G3 C3 E3 D3 C3 D3 E3 C3 | B3 D3 F3 E3 D3 E3 F3 D3 | C4 E3 G3 F3 E3 F3 G3 E3 | D4 F3 A3 G3 F3 G3 A3 F3 | E4 G3 B3 A3 G3 A3 B3 G3 | F4 A3 C4 B3 A3 B3 C4 A3 | G4 B3 D4 C4 B3 C4 D4 B3 | A4 C4 E4 D4 C4 D4 E4 C4 | B4 D4 F4 E4 D4 E4 F4 D4 | C5 E4 G4 F4 E4 F4 G4 E4 | D5 F4 A4 G4 F4 G4 A4 F4 | E5 G4 B4 A4 G4 A4 B4 G4 | F5 A4 C5 B4 A4 B4 C5 A4 | G5 B4 D5 C5 B4 C5 D5 E5 | B4 G5 E5 F5 G5 F5 E5 G5 | A4 F5 D5 E5 F5 E5 D5 F5 | G4 E5 C5 D5 E5 D5 C5 E5 | F4 D5 B4 C5 D5 C5 B4 D5 | E4 C5 A4 B4 C5 B4 A4 C5 | D4 B4 G4 A4 B4 A4 G4 B4 | C4 A4 F4 G4 A4 G4 F4 A4 | B3 G4 E4 F4 G4 F4 E4 G4 | A3 F4 D4 E4 F4 E4 D4 F4 | G3 E4 C4 D4 E4 D4 C4 E4 | F3 D4 B3 C4 D4 C4 B3 D4 | E3 C4 A3 B3 C4 B3 A3 C4 | D3 B3 G3 A3 B3 A3 G3 B3 | C3 A3 F3 G3 A3 G3 F3 A3 | C3 G3 E3 F3 G3 F3 E3 F3 | C3',
    left: 'G2 C2 E2 D2 C2 D2 E2 C2 | B2 D2 F2 E2 D2 E2 F2 D2 | C3 E2 G2 F2 E2 F2 G2 E2 | D3 F2 A2 G2 F2 G2 A2 F2 | E3 G2 B2 A2 G2 A2 B2 G2 | F3 A2 C3 B2 A2 B2 C3 A2 | G3 B2 D3 C3 B2 C3 D3 B2 | A3 C3 E3 D3 C3 D3 E3 C3 | B3 D3 F3 E3 D3 E3 F3 D3 | C4 E3 G3 F3 E3 F3 G3 E3 | D4 F3 A3 G3 F3 G3 A3 F3 | E4 G3 B3 A3 G3 A3 B3 G3 | F4 A3 C4 B3 A3 B3 C4 A3 | G4 B3 D4 C4 B3 C4 D4 E4 | B3 G4 E4 F4 G4 F4 E4 G4 | A3 F4 D4 E4 F4 E4 D4 F4 | G3 E4 C4 D4 E4 D4 C4 E4 | F3 D4 B3 C4 D4 C4 B3 D4 | E3 C4 A3 B3 C4 B3 A3 C4 | D3 B3 G3 A3 B3 A3 G3 B3 | C3 A3 F3 G3 A3 G3 F3 A3 | B2 G3 E3 F3 G3 F3 E3 G3 | A2 F3 D3 E3 F3 E3 D3 F3 | G2 E3 C3 D3 E3 D3 C3 E3 | F2 D3 B2 C3 D3 C3 B2 D3 | E2 C3 A2 B2 C3 B2 A2 C3 | D2 B2 G2 A2 B2 A2 G2 B2 | C2 A2 F2 G2 A2 G2 F2 A2 | C2 G2 E2 F2 G2 F2 E2 F2 | C2',
    rightFingers:
      '51321231 | 51321... | 513..... | 513..... | 513..... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 15345435 | 153..... | 153..... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | .',
    leftFingers:
      '15345435 | 15345... | 153..... | 153..... | 153..... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 51321231 | 513..... | 513..... | 513..... | 513..... | 51...... | 513..... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | .',
  },
  {
    number: 13,
    page: 14,
    beats: 2,
    up: 14,
    right:
      'E3 C3 F3 D3 G3 E3 F3 G3 | F3 D3 G3 E3 A3 F3 G3 A3 | G3 E3 A3 F3 B3 G3 A3 B3 | A3 F3 B3 G3 C4 A3 B3 C4 | B3 G3 C4 A3 D4 B3 C4 D4 | C4 A3 D4 B3 E4 C4 D4 E4 | D4 B3 E4 C4 F4 D4 E4 F4 | E4 C4 F4 D4 G4 E4 F4 G4 | F4 D4 G4 E4 A4 F4 G4 A4 | G4 E4 A4 F4 B4 G4 A4 B4 | A4 F4 B4 G4 C5 A4 B4 C5 | B4 G4 C5 A4 D5 B4 C5 D5 | C5 A4 D5 B4 E5 C5 D5 E5 | D5 B4 E5 C5 F5 D5 E5 F5 | E5 G5 D5 F5 E5 C5 D5 E5 | D5 F5 C5 E5 D5 B4 C5 D5 | C5 E5 B4 D5 C5 A4 B4 C5 | B4 D5 A4 C5 B4 G4 A4 B4 | A4 C5 G4 B4 A4 F4 G4 A4 | G4 B4 F4 A4 G4 E4 F4 G4 | F4 A4 E4 G4 F4 D4 E4 F4 | E4 G4 D4 F4 E4 C4 D4 E4 | D4 F4 C4 E4 D4 B3 C4 D4 | C4 E4 B3 D4 C4 A3 B3 C4 | B3 D4 A3 C4 B3 G3 A3 B3 | A3 C4 G3 B3 A3 F3 G3 A3 | G3 B3 F3 A3 G3 E3 F3 G3 | F3 A3 E3 G3 F3 D3 E3 F3 | C3',
    left: 'E2 C2 F2 D2 G2 E2 F2 G2 | F2 D2 G2 E2 A2 F2 G2 A2 | G2 E2 A2 F2 B2 G2 A2 B2 | A2 F2 B2 G2 C3 A2 B2 C3 | B2 G2 C3 A2 D3 B2 C3 D3 | C3 A2 D3 B2 E3 C3 D3 E3 | D3 B2 E3 C3 F3 D3 E3 F3 | E3 C3 F3 D3 G3 E3 F3 G3 | F3 D3 G3 E3 A3 F3 G3 A3 | G3 E3 A3 F3 B3 G3 A3 B3 | A3 F3 B3 G3 C4 A3 B3 C4 | B3 G3 C4 A3 D4 B3 C4 D4 | C4 A3 D4 B3 E4 C4 D4 E4 | D4 B3 E4 C4 F4 D4 E4 F4 | E4 G4 D4 F4 E4 C4 D4 E4 | D4 F4 C4 E4 D4 B3 C4 D4 | C4 E4 B3 D4 C4 A3 B3 C4 | B3 D4 A3 C4 B3 G3 A3 B3 | A3 C4 G3 B3 A3 F3 G3 A3 | G3 B3 F3 A3 G3 E3 F3 G3 | F3 A3 E3 G3 F3 D3 E3 F3 | E3 G3 D3 F3 E3 C3 D3 E3 | D3 F3 C3 E3 D3 B2 C3 D3 | C3 E3 B2 D3 C3 A2 B2 C3 | B2 D3 A2 C3 B2 G2 A2 B2 | A2 C3 G2 B2 A2 F2 G2 A2 | G2 B2 F2 A2 G2 E2 F2 G2 | F2 A2 E2 G2 F2 D2 E2 F2 | C2',
    rightFingers:
      '31425345 | 31425345 | 31425... | 31...... | 31...... | 31...... | 31...... | 31...... | 31...... | 31...... | 31...... | 31...... | 31...... | 31...... | 35243134 | 35243134 | 35...134 | 35...134 | 35...134 | .....134 | .....134 | .....134 | .....134 | .....134 | .....134 | .....134 | .....134 | .....134 | .',
    leftFingers:
      '35241321 | 35241321 | 35241... | 35...... | 35...... | 35...... | 35...... | 35...... | 35...... | 35...... | 35...... | 35...... | 35...... | 35...... | 31423532 | 31423532 | 31...532 | 31...532 | 31...532 | .....532 | .....532 | .....532 | .....532 | .....532 | .....532 | .....532 | .....532 | .....532 | .',
  },
  {
    number: 14,
    page: 15,
    beats: 2,
    up: 14,
    right:
      'C3 D3 F3 E3 F3 E3 G3 F3 | D3 E3 G3 F3 G3 F3 A3 G3 | E3 F3 A3 G3 A3 G3 B3 A3 | F3 G3 B3 A3 B3 A3 C4 B3 | G3 A3 C4 B3 C4 B3 D4 C4 | A3 B3 D4 C4 D4 C4 E4 D4 | B3 C4 E4 D4 E4 D4 F4 E4 | C4 D4 F4 E4 F4 E4 G4 F4 | D4 E4 G4 F4 G4 F4 A4 G4 | E4 F4 A4 G4 A4 G4 B4 A4 | F4 G4 B4 A4 B4 A4 C5 B4 | G4 A4 C5 B4 C5 B4 D5 C5 | A4 B4 D5 C5 D5 C5 E5 D5 | B4 C5 E5 D5 E5 D5 F5 E5 | G5 F5 D5 E5 D5 E5 C5 D5 | F5 E5 C5 D5 C5 D5 B4 C5 | E5 D5 B4 C5 B4 C5 A4 B4 | D5 C5 A4 B4 A4 B4 G4 A4 | C5 B4 G4 A4 G4 A4 F4 G4 | B4 A4 F4 G4 F4 G4 E4 F4 | A4 G4 E4 F4 E4 F4 D4 E4 | G4 F4 D4 E4 D4 E4 C4 D4 | F4 E4 C4 D4 C4 D4 B3 C4 | E4 D4 B3 C4 B3 C4 A3 B3 | D4 C4 A3 B3 A3 B3 G3 A3 | C4 B3 G3 A3 G3 A3 F3 G3 | B3 A3 F3 G3 F3 G3 E3 F3 | A3 G3 E3 F3 E3 F3 D3 E3 | C3',
    left: 'C2 D2 F2 E2 F2 E2 G2 F2 | D2 E2 G2 F2 G2 F2 A2 G2 | E2 F2 A2 G2 A2 G2 B2 A2 | F2 G2 B2 A2 B2 A2 C3 B2 | G2 A2 C3 B2 C3 B2 D3 C3 | A2 B2 D3 C3 D3 C3 E3 D3 | B2 C3 E3 D3 E3 D3 F3 E3 | C3 D3 F3 E3 F3 E3 G3 F3 | D3 E3 G3 F3 G3 F3 A3 G3 | E3 F3 A3 G3 A3 G3 B3 A3 | F3 G3 B3 A3 B3 A3 C4 B3 | G3 A3 C4 B3 C4 B3 D4 C4 | A3 B3 D4 C4 D4 C4 E4 D4 | B3 C4 E4 D4 E4 D4 F4 E4 | G4 F4 D4 E4 D4 E4 C4 D4 | F4 E4 C4 D4 C4 D4 B3 C4 | E4 D4 B3 C4 B3 C4 A3 B3 | D4 C4 A3 B3 A3 B3 G3 A3 | C4 B3 G3 A3 G3 A3 F3 G3 | B3 A3 F3 G3 F3 G3 E3 F3 | A3 G3 E3 F3 E3 F3 D3 E3 | G3 F3 D3 E3 D3 E3 C3 D3 | F3 E3 C3 D3 C3 D3 B2 C3 | E3 D3 B2 C3 B2 C3 A2 B2 | D3 C3 A2 B2 A2 B2 G2 A2 | C3 B2 G2 A2 G2 A2 F2 G2 | B2 A2 F2 G2 F2 G2 E2 F2 | A2 G2 E2 F2 E2 F2 D2 E2 | C2',
    rightFingers:
      '12434354 | 12434354 | 1243..54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....53 | 54232313 | 542...13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | .',
    leftFingers:
      '54232313 | 54232313 | 542...13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 5.....13 | 12434354 | 124...54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....54 | 1.....53 | .',
  },
  {
    number: 15,
    page: 16,
    beats: 2,
    up: 14,
    right:
      'C3 E3 D3 F3 E3 G3 F3 A3 | D3 F3 E3 G3 F3 A3 G3 B3 | E3 G3 F3 A3 G3 B3 A3 C4 | F3 A3 G3 B3 A3 C4 B3 D4 | G3 B3 A3 C4 B3 D4 C4 E4 | A3 C4 B3 D4 C4 E4 D4 F4 | B3 D4 C4 E4 D4 F4 E4 G4 | C4 E4 D4 F4 E4 G4 F4 A4 | D4 F4 E4 G4 F4 A4 G4 B4 | E4 G4 F4 A4 G4 B4 A4 C5 | F4 A4 G4 B4 A4 C5 B4 D5 | G4 B4 A4 C5 B4 D5 C5 E5 | A4 C5 B4 D5 C5 E5 D5 F5 | B4 D5 C5 E5 D5 F5 E5 F5 | G5 E5 F5 D5 E5 C5 D5 B4 | F5 D5 E5 C5 D5 B4 C5 A4 | E5 C5 D5 B4 C5 A4 B4 G4 | D5 B4 C5 A4 B4 G4 A4 F4 | C5 A4 B4 G4 A4 F4 G4 E4 | B4 G4 A4 F4 G4 E4 F4 D4 | A4 F4 G4 E4 F4 D4 E4 C4 | G4 E4 F4 D4 E4 C4 D4 B3 | F4 D4 E4 C4 D4 B3 C4 A3 | E4 C4 D4 B3 C4 A3 B3 G3 | D4 B3 C4 A3 B3 G3 A3 F3 | C4 A3 B3 G3 A3 F3 G3 E3 | B3 G3 A3 F3 G3 E3 F3 D3 | A3 F3 G3 E3 F3 D3 E3 D3 | C3',
    left: 'C2 E2 D2 F2 E2 G2 F2 A2 | D2 F2 E2 G2 F2 A2 G2 B2 | E2 G2 F2 A2 G2 B2 A2 C3 | F2 A2 G2 B2 A2 C3 B2 D3 | G2 B2 A2 C3 B2 D3 C3 E3 | A2 C3 B2 D3 C3 E3 D3 F3 | B2 D3 C3 E3 D3 F3 E3 G3 | C3 E3 D3 F3 E3 G3 F3 A3 | D3 F3 E3 G3 F3 A3 G3 B3 | E3 G3 F3 A3 G3 B3 A3 C4 | F3 A3 G3 B3 A3 C4 B3 D4 | G3 B3 A3 C4 B3 D4 C4 E4 | A3 C4 B3 D4 C4 E4 D4 F4 | B3 D4 C4 E4 D4 F4 E4 F4 | G4 E4 F4 D4 E4 C4 D4 B3 | F4 D4 E4 C4 D4 B3 C4 A3 | E4 C4 D4 B3 C4 A3 B3 G3 | D4 B3 C4 A3 B3 G3 A3 F3 | C4 A3 B3 G3 A3 F3 G3 E3 | B3 G3 A3 F3 G3 E3 F3 D3 | A3 F3 G3 E3 F3 D3 E3 C3 | G3 E3 F3 D3 E3 C3 D3 B2 | F3 D3 E3 C3 D3 B2 C3 A2 | E3 C3 D3 B2 C3 A2 B2 G2 | D3 B2 C3 A2 B2 G2 A2 F2 | C3 A2 B2 G2 A2 F2 G2 E2 | B2 G2 A2 F2 G2 E2 F2 D2 | A2 F2 G2 E2 F2 D2 E2 D2 | C2',
    rightFingers:
      '12132435 | 12132435 | 121324.. | 12132... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213..34 | 53423121 | 53423121 | 5...3121 | ......21 | ......21 | ......21 | ......21 | ......21 | ......21 | ......21 | ......21 | ......21 | ......21 | ....3132 | .',
    leftFingers:
      '53423121 | 53423121 | 53423121 | 5...3121 | 5...3121 | 5...3121 | ....3121 | ....3121 | ....3121 | ....3121 | ....3121 | ....3121 | ....3121 | ....3132 | 12132435 | 12132435 | 12132... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213.... | 1213..34 | .',
  },
  {
    number: 16,
    page: 17,
    beats: 2,
    up: 14,
    right:
      'C3 E3 D3 E3 A3 G3 F3 G3 | D3 F3 E3 F3 B3 A3 G3 A3 | E3 G3 F3 G3 C4 B3 A3 B3 | F3 A3 G3 A3 D4 C4 B3 C4 | G3 B3 A3 B3 E4 D4 C4 D4 | A3 C4 B3 C4 F4 E4 D4 E4 | B3 D4 C4 D4 G4 F4 E4 F4 | C4 E4 D4 E4 A4 G4 F4 G4 | D4 F4 E4 F4 B4 A4 G4 A4 | E4 G4 F4 G4 C5 B4 A4 B4 | F4 A4 G4 A4 D5 C5 B4 C5 | G4 B4 A4 B4 E5 D5 C5 D5 | A4 C5 B4 C5 F5 E5 D5 E5 | B4 D5 C5 D5 G5 F5 E5 F5 | G5 D5 E5 D5 B4 C5 D5 C5 | F5 C5 D5 C5 A4 B4 C5 B4 | E5 B4 C5 B4 G4 A4 B4 A4 | D5 A4 B4 A4 F4 G4 A4 G4 | C5 G4 A4 G4 E4 F4 G4 F4 | B4 F4 G4 F4 D4 E4 F4 E4 | A4 E4 F4 E4 C4 D4 E4 D4 | G4 D4 E4 D4 B3 C4 D4 C4 | F4 C4 D4 C4 A3 B3 C4 B3 | E4 B3 C4 B3 G3 A3 B3 A3 | D4 A3 B3 A3 F3 G3 A3 G3 | C4 G3 A3 G3 E3 F3 G3 F3 | B3 F3 G3 F3 D3 E3 F3 E3 | A3 E3 F3 E3 C3 D3 E3 D3 | C3',
    left: 'C2 E2 D2 E2 A2 G2 F2 G2 | D2 F2 E2 F2 B2 A2 G2 A2 | E2 G2 F2 G2 C3 B2 A2 B2 | F2 A2 G2 A2 D3 C3 B2 C3 | G2 B2 A2 B2 E3 D3 C3 D3 | A2 C3 B2 C3 F3 E3 D3 E3 | B2 D3 C3 D3 G3 F3 E3 F3 | C3 E3 D3 E3 A3 G3 F3 G3 | D3 F3 E3 F3 B3 A3 G3 A3 | E3 G3 F3 G3 C4 B3 A3 B3 | F3 A3 G3 A3 D4 C4 B3 C4 | G3 B3 A3 B3 E4 D4 C4 D4 | A3 C4 B3 C4 F4 E4 D4 E4 | B3 D4 C4 D4 G4 F4 E4 F4 | G4 D4 E4 D4 B3 C4 D4 C4 | F4 C4 D4 C4 A3 B3 C4 B3 | E4 B3 C4 B3 G3 A3 B3 A3 | D4 A3 B3 A3 F3 G3 A3 G3 | C4 G3 A3 G3 E3 F3 G3 F3 | B3 F3 G3 F3 D3 E3 F3 E3 | A3 E3 F3 E3 C3 D3 E3 D3 | G3 D3 E3 D3 B2 C3 D3 C3 | F3 C3 D3 C3 A2 B2 C3 B2 | E3 B2 C3 B2 G2 A2 B2 A2 | D3 A2 B2 A2 F2 G2 A2 G2 | C3 G2 A2 G2 E2 F2 G2 F2 | B2 F2 G2 F2 D2 E2 F2 E2 | A2 E2 F2 E2 C2 D2 E2 D2 | C2',
    rightFingers:
      '13235434 | 13235... | 13235... | 13..5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 52321232 | 52321232 | 52..1... | 52..1... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | 52...... | .',
    leftFingers:
      '53431232 | 53431... | 53431... | 53..1... | 53..1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 13235434 | 13235434 | 13..5... | 13..5... | 13..5... | 13..5... | 13..5... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | 13...... | .',
  },
  {
    number: 17,
    page: 18,
    beats: 2,
    up: 14,
    right:
      'C3 E3 A3 G3 B3 A3 G3 A3 | D3 F3 B3 A3 C4 B3 A3 B3 | E3 G3 C4 B3 D4 C4 B3 C4 | F3 A3 D4 C4 E4 D4 C4 D4 | G3 B3 E4 D4 F4 E4 D4 E4 | A3 C4 F4 E4 G4 F4 E4 F4 | B3 D4 G4 F4 A4 G4 F4 G4 | C4 E4 A4 G4 B4 A4 G4 A4 | D4 F4 B4 A4 C5 B4 A4 B4 | E4 G4 C5 B4 D5 C5 B4 C5 | F4 A4 D5 C5 E5 D5 C5 D5 | G4 B4 E5 D5 F5 E5 D5 E5 | A4 C5 F5 E5 G5 F5 E5 F5 | B4 D5 G5 F5 A5 G5 F5 E5 | G5 D5 B4 C5 A4 B4 C5 A4 | F5 C5 A4 B4 G4 A4 B4 G4 | E5 B4 G4 A4 F4 G4 A4 F4 | D5 A4 F4 G4 E4 F4 G4 E4 | C5 G4 E4 F4 D4 E4 F4 D4 | B4 F4 D4 E4 C4 D4 E4 C4 | A4 E4 C4 D4 B3 C4 D4 B3 | G4 D4 B3 C4 A3 B3 C4 A3 | F4 C4 A3 B3 G3 A3 B3 G3 | E4 B3 G3 A3 F3 G3 A3 F3 | D4 A3 F3 G3 E3 F3 G3 E3 | C4 G3 E3 F3 D3 E3 F3 D3 | B3 F3 D3 E3 C3 D3 E3 D3 | C3',
    left: 'C2 E2 A2 G2 B2 A2 G2 A2 | D2 F2 B2 A2 C3 B2 A2 B2 | E2 G2 C3 B2 D3 C3 B2 C3 | F2 A2 D3 C3 E3 D3 C3 D3 | G2 B2 E3 D3 F3 E3 D3 E3 | A2 C3 F3 E3 G3 F3 E3 F3 | B2 D3 G3 F3 A3 G3 F3 G3 | C3 E3 A3 G3 B3 A3 G3 A3 | D3 F3 B3 A3 C4 B3 A3 B3 | E3 G3 C4 B3 D4 C4 B3 C4 | F3 A3 D4 C4 E4 D4 C4 D4 | G3 B3 E4 D4 F4 E4 D4 E4 | A3 C4 F4 E4 G4 F4 E4 F4 | B3 D4 G4 F4 A4 G4 F4 E4 | G4 D4 B3 C4 A3 B3 C4 A3 | F4 C4 A3 B3 G3 A3 B3 G3 | E4 B3 G3 A3 F3 G3 A3 F3 | D4 A3 F3 G3 E3 F3 G3 E3 | C4 G3 E3 F3 D3 E3 F3 D3 | B3 F3 D3 E3 C3 D3 E3 C3 | A3 E3 C3 D3 B2 C3 D3 B2 | G3 D3 B2 C3 A2 B2 C3 A2 | F3 C3 A2 B2 G2 A2 B2 G2 | E3 B2 G2 A2 F2 G2 A2 F2 | D3 A2 F2 G2 E2 F2 G2 E2 | C3 G2 E2 F2 D2 E2 F2 D2 | B2 F2 D2 E2 C2 D2 E2 D2 | C2',
    rightFingers:
      '12435434 | 12435434 | 124.5... | 124.5... | 124.5... | 124.5... | 124..... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 12435432 | 53231231 | 53231... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | 532.1... | .',
    leftFingers:
      '54231232 | 54231232 | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1... | 542.1234 | 12435435 | 12435... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | 124.5... | .',
  },
  {
    number: 18,
    page: 19,
    beats: 2,
    up: 14,
    right:
      'C3 D3 F3 E3 G3 F3 D3 E3 | D3 E3 G3 F3 A3 G3 E3 F3 | E3 F3 A3 G3 B3 A3 F3 G3 | F3 G3 B3 A3 C4 B3 G3 A3 | G3 A3 C4 B3 D4 C4 A3 B3 | A3 B3 D4 C4 E4 D4 B3 C4 | B3 C4 E4 D4 F4 E4 C4 D4 | C4 D4 F4 E4 G4 F4 D4 E4 | D4 E4 G4 F4 A4 G4 E4 F4 | E4 F4 A4 G4 B4 A4 F4 G4 | F4 G4 B4 A4 C5 B4 G4 A4 | G4 A4 C5 B4 D5 C5 A4 B4 | A4 B4 D5 C5 E5 D5 B4 C5 | B4 C5 E5 D5 F5 E5 C5 D5 | G5 F5 D5 E5 C5 D5 F5 E5 | F5 E5 C5 D5 B4 C5 E5 D5 | E5 D5 B4 C5 A4 B4 D5 C5 | D5 C5 A4 B4 G4 A4 C5 B4 | C5 B4 G4 A4 F4 G4 B4 A4 | B4 A4 F4 G4 E4 F4 A4 G4 | A4 G4 E4 F4 D4 E4 G4 F4 | G4 F4 D4 E4 C4 D4 F4 E4 | F4 E4 C4 D4 B3 C4 E4 D4 | E4 D4 B3 C4 A3 B3 D4 C4 | D4 C4 A3 B3 G3 A3 C4 B3 | C4 B3 G3 A3 F3 G3 B3 A3 | B3 A3 F3 G3 E3 F3 A3 G3 | A3 G3 E3 F3 D3 E3 G3 F3 | C3',
    left: 'C2 D2 F2 E2 G2 F2 D2 E2 | D2 E2 G2 F2 A2 G2 E2 F2 | E2 F2 A2 G2 B2 A2 F2 G2 | F2 G2 B2 A2 C3 B2 G2 A2 | G2 A2 C3 B2 D3 C3 A2 B2 | A2 B2 D3 C3 E3 D3 B2 C3 | B2 C3 E3 D3 F3 E3 C3 D3 | C3 D3 F3 E3 G3 F3 D3 E3 | D3 E3 G3 F3 A3 G3 E3 F3 | E3 F3 A3 G3 B3 A3 F3 G3 | F3 G3 B3 A3 C4 B3 G3 A3 | G3 A3 C4 B3 D4 C4 A3 B3 | A3 B3 D4 C4 E4 D4 B3 C4 | B3 C4 E4 D4 F4 E4 C4 D4 | G4 F4 D4 E4 C4 D4 F4 E4 | F4 E4 C4 D4 B3 C4 E4 D4 | E4 D4 B3 C4 A3 B3 D4 C4 | D4 C4 A3 B3 G3 A3 C4 B3 | C4 B3 G3 A3 F3 G3 B3 A3 | B3 A3 F3 G3 E3 F3 A3 G3 | A3 G3 E3 F3 D3 E3 G3 F3 | G3 F3 D3 E3 C3 D3 F3 E3 | F3 E3 C3 D3 B2 C3 E3 D3 | E3 D3 B2 C3 A2 B2 D3 C3 | D3 C3 A2 B2 G2 A2 C3 B2 | C3 B2 G2 A2 F2 G2 B2 A2 | B2 A2 F2 G2 E2 F2 A2 G2 | A2 G2 E2 F2 D2 E2 G2 F2 | C2',
    rightFingers:
      '12435423 | 124.5... | 124.5... | 124.5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5... | 1...5.12 | 54231243 | 54231.43 | 542.1.43 | 54....43 | 54....43 | 54....43 | 54....43 | 5.....43 | 5.....43 | 5.....43 | 5.....43 | 5.....43 | 5.....43 | 5...1354 | 1',
    leftFingers:
      '54231243 | 542.1... | 542.1... | 542.1... | 5...1... | 5...1... | ....1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1... | 5...1.54 | 12435423 | 12435423 | 124.5.23 | 12....23 | 12....23 | 1.....23 | 1.....23 | 1.....23 | 1.....23 | 1.....23 | 1.....23 | 1.....23 | 1.....23 | 1.....12 | 5',
  },
  {
    number: 19,
    page: 20,
    beats: 2,
    up: 14,
    right:
      'C3 A3 F3 G3 A3 F3 E3 G3 | D3 B3 G3 A3 B3 G3 F3 A3 | E3 C4 A3 B3 C4 A3 G3 B3 | F3 D4 B3 C4 D4 B3 A3 C4 | G3 E4 C4 D4 E4 C4 B3 D4 | A3 F4 D4 E4 F4 D4 C4 E4 | B3 G4 E4 F4 G4 E4 D4 F4 | C4 A4 F4 G4 A4 F4 E4 G4 | D4 B4 G4 A4 B4 G4 F4 A4 | E4 C5 A4 B4 C5 A4 G4 B4 | F4 D5 B4 C5 D5 B4 A4 C5 | G4 E5 C5 D5 E5 C5 B4 D5 | A4 F5 D5 E5 F5 D5 C5 E5 | B4 G5 E5 F5 G5 E5 D5 F5 | G5 B4 D5 C5 B4 D5 E5 C5 | F5 A4 C5 B4 A4 C5 D5 B4 | E5 G4 B4 A4 G4 B4 C5 A4 | D5 F4 A4 G4 F4 A4 B4 G4 | C5 E4 G4 F4 E4 G4 A4 F4 | B4 D4 F4 E4 D4 F4 G4 E4 | A4 C4 E4 D4 C4 E4 F4 D4 | G4 B3 D4 C4 B3 D4 E4 C4 | F4 A3 C4 B3 A3 C4 D4 B3 | E4 G3 B3 A3 G3 B3 C4 A3 | D4 F3 A3 G3 F3 A3 B3 G3 | C4 E3 G3 F3 E3 G3 A3 F3 | B3 D3 F3 E3 D3 F3 G3 E3 | A3 C3 E3 D3 C3 E3 F3 D3 | C3',
    left: 'C2 A2 F2 G2 A2 F2 E2 G2 | D2 B2 G2 A2 B2 G2 F2 A2 | E2 C3 A2 B2 C3 A2 G2 B2 | F2 D3 B2 C3 D3 B2 A2 C3 | G2 E3 C3 D3 E3 C3 B2 D3 | A2 F3 D3 E3 F3 D3 C3 E3 | B2 G3 E3 F3 G3 E3 D3 F3 | C3 A3 F3 G3 A3 F3 E3 G3 | D3 B3 G3 A3 B3 G3 F3 A3 | E3 C4 A3 B3 C4 A3 G3 B3 | F3 D4 B3 C4 D4 B3 A3 C4 | G3 E4 C4 D4 E4 C4 B3 D4 | A3 F4 D4 E4 F4 D4 C4 E4 | B3 G4 E4 F4 G4 E4 D4 F4 | G4 B3 D4 C4 B3 D4 E4 C4 | F4 A3 C4 B3 A3 C4 D4 B3 | E4 G3 B3 A3 G3 B3 C4 A3 | D4 F3 A3 G3 F3 A3 B3 G3 | C4 E3 G3 F3 E3 G3 A3 F3 | B3 D3 F3 E3 D3 F3 G3 E3 | A3 C3 E3 D3 C3 E3 F3 D3 | G3 B2 D3 C3 B2 D3 E3 C3 | F3 A2 C3 B2 A2 C3 D3 B2 | E3 G2 B2 A2 G2 B2 C3 A2 | D3 F2 A2 G2 F2 A2 B2 G2 | C3 E2 G2 F2 E2 G2 A2 F2 | B2 D2 F2 E2 D2 F2 G2 E2 | A2 C2 E2 D2 C2 E2 F2 D2 | C2',
    rightFingers:
      '15345324 | 15345324 | 153..... | 153..... | 153..... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 15...... | 51321342 | 513.1342 | 51..1342 | 51..1342 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | 5.....42 | .',
    leftFingers:
      '51321342 | 51321342 | 513..... | 513..... | 513..... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 51...... | 15345324 | 15345324 | 15..5324 | 15..5324 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | 1.....24 | .',
  },
  {
    number: 20,
    page: 21,
    beats: 2,
    up: 15,
    right:
      'E3 G3 C4 E4 C4 B3 C4 A3 | F3 A3 D4 F4 D4 C4 D4 B3 | G3 B3 E4 G4 E4 D4 E4 C4 | A3 C4 F4 A4 F4 E4 F4 D4 | B3 D4 G4 B4 G4 F4 G4 E4 | C4 E4 A4 C5 A4 G4 A4 F4 | D4 F4 B4 D5 B4 A4 B4 G4 | E4 G4 C5 E5 C5 B4 C5 A4 | F4 A4 D5 F5 D5 C5 D5 B4 | G4 B4 E5 G5 E5 D5 E5 C5 | A4 C5 F5 A5 F5 E5 F5 D5 | B4 D5 G5 B5 G5 F5 G5 E5 | C5 E5 A5 C6 A5 G5 A5 F5 | D5 F5 B5 D6 B5 A5 B5 G5 | E5 G5 C6 E6 C6 B5 C6 G5 | E6 C6 G5 E5 G5 F5 G5 E5 | D6 B5 F5 D5 F5 E5 F5 D5 | C6 A5 E5 C5 E5 D5 E5 C5 | B5 G5 D5 B4 D5 C5 D5 B4 | A5 F5 C5 A4 C5 B4 C5 A4 | G5 E5 B4 G4 B4 A4 B4 G4 | F5 D5 A4 F4 A4 G4 A4 F4 | E5 C5 G4 E4 G4 F4 G4 E4 | D5 B4 F4 D4 F4 E4 F4 D4 | C5 A4 E4 C4 E4 D4 E4 C4 | B4 G4 D4 B3 D4 C4 D4 B3 | A4 F4 C4 A3 C4 B3 C4 A3 | G4 E4 B3 G3 B3 A3 B3 G3 | F4 D4 A3 F3 A3 G3 A3 F3 | E4 C4 G3 E3 G3 F3 G3 F3 | E3+C4',
    left: 'E2 G2 C3 E3 C3 B2 C3 A2 | F2 A2 D3 F3 D3 C3 D3 B2 | G2 B2 E3 G3 E3 D3 E3 C3 | A2 C3 F3 A3 F3 E3 F3 D3 | B2 D3 G3 B3 G3 F3 G3 E3 | C3 E3 A3 C4 A3 G3 A3 F3 | D3 F3 B3 D4 B3 A3 B3 G3 | E3 G3 C4 E4 C4 B3 C4 A3 | F3 A3 D4 F4 D4 C4 D4 B3 | G3 B3 E4 G4 E4 D4 E4 C4 | A3 C4 F4 A4 F4 E4 F4 D4 | B3 D4 G4 B4 G4 F4 G4 E4 | C4 E4 A4 C5 A4 G4 A4 F4 | D4 F4 B4 D5 B4 A4 B4 G4 | E4 G4 C5 E5 C5 B4 C5 G4 | E5 C5 G4 E4 G4 F4 G4 E4 | D5 B4 F4 D4 F4 E4 F4 D4 | C5 A4 E4 C4 E4 D4 E4 C4 | B4 G4 D4 B3 D4 C4 D4 B3 | A4 F4 C4 A3 C4 B3 C4 A3 | G4 E4 B3 G3 B3 A3 B3 G3 | F4 D4 A3 F3 A3 G3 A3 F3 | E4 C4 G3 E3 G3 F3 G3 E3 | D4 B3 F3 D3 F3 E3 F3 D3 | C4 A3 E3 C3 E3 D3 E3 C3 | B3 G3 D3 B2 D3 C3 D3 B2 | A3 F3 C3 A2 C3 B2 C3 A2 | G3 E3 B2 G2 B2 A2 B2 G2 | F3 D3 A2 F2 A2 G2 A2 F2 | E3 C3 G2 E2 G2 F2 G2 F2 | C2+C3',
    rightFingers:
      '12454342 | 12454342 | 12454..2 | 12454... | 12454..2 | 12454..2 | 124.4... | 124....2 | 124....2 | 124....2 | 124....2 | 124....2 | 124....2 | 124....2 | 124....2 | 54213231 | 54213... | 54213... | 54213... | 54213... | 54213... | 542.3... | 542.3... | 54213... | 54213... | 54213... | 542.3... | 542.3... | 542.3... | 542.3... | .',
    leftFingers:
      '54212324 | 54212324 | 54212..4 | 54212... | 5421...4 | 5421...4 | 5421...4 | 5421...4 | 5421...4 | 5421...4 | 542....4 | 542....4 | 542....4 | 542....4 | 542....4 | 12453435 | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | 12453... | .',
  },
];
