import { describe, expect, it } from 'vitest';
import s7Json from '../../scripts/scales/hanon/s7/s7.json?raw';
import { HANON_PARTS } from './hanonTechnique.ts';
import { readTechnique, renderTechniqueModule, techniqueData } from './hanonTechniqueData.ts';
import { fnv1a } from './pieceRecords.ts';

const entries = readTechnique(JSON.parse(s7Json) as unknown);

describe('hanonTechnique.ts (generated from s7.json)', () => {
  // The module is generated; rebuilding its data from the transcription must give what is
  // committed, so neither can change without the other (run scripts/scales/hanonTechnique.ts).
  it('holds exactly the data scripts/scales/hanonTechnique.ts builds from s7.json', () => {
    expect(techniqueData(entries)).toEqual(HANON_PARTS);
  });

  it('renders to a module with the same export', () => {
    const source = renderTechniqueModule(techniqueData(entries));
    expect(source).toMatch(/^\/\/ Generated by scripts\/scales\/hanonTechnique\.ts/);
    expect(source).toContain('IMSLP #91547');
    expect(source).toContain('export const HANON_PARTS');
  });

  /**
   * Locks every note and finger: a deliberate change to the transcription must update this line
   * (and say why in the commit).
   */
  it('is locked by checksum', () => {
    const all = HANON_PARTS.map(
      (p) =>
        `${p.number}:${p.part}:${p.beats}:${p.perBeat}:${p.right}|${p.left}|${p.rightFingers}|${p.leftFingers}` +
        (p.rest ? `|rest ${p.rest}` : ''),
    ).join(';');
    expect(fnv1a(all)).toBe('286ca8e0');
  });

  it('takes No. 53’s footnote: the 4th finger on each black-key octave, and nothing else', () => {
    for (const p of HANON_PARTS.filter((x) => x.number === 53)) {
      const digits = `${p.rightFingers} ${p.leftFingers}`.replace(/[|\s.]/g, '');
      expect(/^4*$/.test(digits), p.part).toBe(true);
    }
  });
});
