import { describe, expect, it } from 'vitest';
import {
  CORRECTIONS,
  fingeringData,
  readHanon,
  readHanonArpeggios,
  renderFingeringModule,
} from './hanonData.ts';
import hanonJson from '../../scripts/scales/hanon/hanon.json?raw';
import hanon41Json from '../../scripts/scales/hanon/hanon41.json?raw';
import { fnv1a } from './pieceRecords.ts';
import {
  HANON_ARPEGGIOS,
  HANON_CHROMATIC,
  HANON_CORRECTIONS,
  HANON_EDITION,
  HANON_SCALES,
} from './scaleFingering.ts';

const hanon = readHanon(JSON.parse(hanonJson) as unknown);
const hanon41 = readHanonArpeggios(JSON.parse(hanon41Json) as unknown);

describe('scaleFingering.ts (generated from hanon.json)', () => {
  // The module is generated; rebuilding its data from the transcription must give what is
  // committed, so neither can change without the other (run scripts/scales/fingering.ts).
  it('holds exactly the data scripts/scales/fingering.ts builds from hanon.json', () => {
    expect(fingeringData(hanon, hanon41)).toEqual({
      scales: HANON_SCALES,
      chromatic: HANON_CHROMATIC,
      arpeggios: HANON_ARPEGGIOS,
      corrections: HANON_CORRECTIONS,
    });
  });

  it('renders to a module with the same exports', () => {
    const source = renderFingeringModule(fingeringData(hanon, hanon41));
    expect(source).toMatch(/^\/\/ Generated by scripts\/scales\/fingering\.ts/);
    expect(source).toContain('IMSLP #91547');
    expect(source).toContain('Nos. 39, 40 and 41');
    for (const name of [
      'HANON_EDITION',
      'HANON_CORRECTIONS',
      'HANON_SCALES',
      'HANON_CHROMATIC',
      'HANON_ARPEGGIOS',
    ])
      expect(source).toContain(`export const ${name}`);
  });

  /**
   * Locks every finger: a deliberate change to the transcription or the corrections must update
   * this line (and say why in the commit).
   */
  it('is locked by checksum', () => {
    const all = [
      ...HANON_SCALES.map(
        (s) => `${s.key}:${s.mode}:${s.rightUp}|${s.rightDown}|${s.leftUp}|${s.leftDown}`,
      ),
      `chromatic:${HANON_CHROMATIC.rightUp}|${HANON_CHROMATIC.rightDown}|${HANON_CHROMATIC.leftUp}|${HANON_CHROMATIC.leftDown}`,
    ].join(';');
    expect({ scales: HANON_SCALES.length, checksum: fnv1a(all) }).toEqual({
      scales: 36,
      checksum: 'f3dc638b',
    });
    const arpeggios = HANON_ARPEGGIOS.map(
      (a) => `${a.key}:${a.mode}:${a.rightUp}|${a.rightDown}|${a.leftUp}|${a.leftDown}`,
    ).join(';');
    expect({ arpeggios: HANON_ARPEGGIOS.length, checksum: fnv1a(arpeggios) }).toEqual({
      arpeggios: 24,
      checksum: '29afb47b',
    });
  });

  it('has No. 41 in every key, in Hanon’s order, each run of 13 notes sharing the top', () => {
    expect(HANON_ARPEGGIOS.map((a) => `${a.key} ${a.mode}`)).toEqual(
      ['C', 'F', 'Bb', 'Eb', 'Ab', 'Db', 'Gb', 'B', 'E', 'A', 'D', 'G'].flatMap((key, i) => [
        `${key} major`,
        `${['A', 'D', 'G', 'C', 'F', 'Bb', 'Eb', 'G#', 'C#', 'F#', 'B', 'E'][i]} minor`,
      ]),
    );
    const digits = (run: string) => run.replace(/ /g, '');
    for (const a of HANON_ARPEGGIOS) {
      for (const run of [a.rightUp, a.rightDown, a.leftUp, a.leftDown])
        expect(digits(run)).toMatch(/^[1-5]{13}$/);
      expect(digits(a.rightUp).at(-1)).toBe(digits(a.rightDown)[0]);
      expect(digits(a.leftUp).at(-1)).toBe(digits(a.leftDown)[0]);
      expect(digits(a.rightDown).at(-1)).toBe(digits(a.rightUp)[0]);
      expect(digits(a.leftDown).at(-1)).toBe(digits(a.leftUp)[0]);
      expect(a.page).toBeGreaterThanOrEqual(65);
      expect(a.page).toBeLessThanOrEqual(68);
    }
  });

  it('names the edition', () => {
    expect(HANON_EDITION).toMatch(/G\. Schirmer/);
    expect(HANON_EDITION).toMatch(/\[1900\]/);
    expect(HANON_EDITION).toMatch(/IMSLP #91547/);
  });

  it('has every major, harmonic and melodic minor of No. 39 once, and no natural minor', () => {
    const keys = HANON_SCALES.map((s) => `${s.key}:${s.mode}`);
    expect(new Set(keys).size).toBe(36);
    expect(HANON_SCALES.filter((s) => s.mode === 'major').map((s) => s.key)).toEqual([
      'C',
      'F',
      'Bb',
      'Eb',
      'Ab',
      'Db',
      'Gb',
      'B',
      'E',
      'A',
      'D',
      'G',
    ]);
    for (const mode of ['harmonicMinor', 'melodicMinor'] as const)
      expect(HANON_SCALES.filter((s) => s.mode === mode).map((s) => s.key)).toEqual([
        'A',
        'D',
        'G',
        'C',
        'F',
        'Bb',
        'Eb',
        'G#',
        'C#',
        'F#',
        'B',
        'E',
      ]);
  });

  it('runs have 29 notes (49 chromatic) and share the top note', () => {
    const digits = (run: string) => run.replace(/ /g, '');
    for (const [runs, length] of [
      ...HANON_SCALES.map((s) => [s, 29] as const),
      [HANON_CHROMATIC, 49] as const,
    ]) {
      for (const run of [runs.rightUp, runs.rightDown, runs.leftUp, runs.leftDown])
        expect(digits(run)).toMatch(new RegExp(`^[1-5]{${length}}$`));
      expect(digits(runs.rightUp).at(-1)).toBe(digits(runs.rightDown)[0]);
      expect(digits(runs.leftUp).at(-1)).toBe(digits(runs.leftDown)[0]);
      // The closing tonic takes the starting finger (docs/SCALES.md).
      expect(digits(runs.rightDown).at(-1)).toBe(digits(runs.rightUp)[0]);
      expect(digits(runs.leftDown).at(-1)).toBe(digits(runs.leftUp)[0]);
    }
  });

  it('takes every digit as transcribed except the one correction, which is recorded', () => {
    expect(HANON_CORRECTIONS).toEqual(CORRECTIONS);
    expect(HANON_CORRECTIONS).toHaveLength(1);
    const [c] = HANON_CORRECTIONS;
    expect(c).toMatchObject({ key: 'D', mode: 'major', run: 'leftDown', index: 27, note: 'E2' });
    expect(c).toMatchObject({ printed: 1, used: 4 });
    for (const entry of hanon) {
      const scale =
        entry.mode === 'chromatic'
          ? HANON_CHROMATIC
          : HANON_SCALES.find((s) => s.key === entry.key && s.mode === entry.mode)!;
      for (const run of ['rightUp', 'rightDown', 'leftUp', 'leftDown'] as const) {
        const ours = [...scale[run].replace(/ /g, '')].map(Number);
        const differs = ours.flatMap((f, i) => (f === entry[run][i] ? [] : [i]));
        const corrected = HANON_CORRECTIONS.filter(
          (x) => x.key === entry.key && x.mode === entry.mode && x.run === run,
        );
        expect(differs).toEqual(corrected.map((x) => x.index));
        for (const x of corrected) {
          expect(entry[run][x.index]).toBe(x.printed);
          expect(ours[x.index]).toBe(x.used);
        }
      }
    }
  });
});
