// Generated by scripts/scales/fingering.ts from scripts/scales/hanon/hanon.json and hanon41.json.
// Do not edit: change the transcription or the corrections there and run
//   node --experimental-strip-types scripts/scales/fingering.ts
//
// Fingering from Charles-Louis Hanon, The Virtuoso Pianist, G. Schirmer, New York, n.d. [1900],
// plate 15538, IMSLP #91547: No. 39 (the major, harmonic minor and melodic minor scales), No. 40
// (the chromatic scale at the octave) and No. 41 (the arpeggios on the major and minor triads), as
// printed there: four octaves, hands an octave apart. How it was read and checked is in
// scripts/scales/hanon/README.md.
//
// Each run is a string of fingers, one digit per note, grouped by octave for reading (spaces carry
// no meaning). `…Up` goes from the tonic to the top note inclusive, `…Down` from the top note back
// to the tonic inclusive, so the top note is the last digit of one and the first of the other.
// Hanon never prints the closing tonic of a scale (his run repeats); it takes his starting finger.
// Melodic minor goes down as the natural minor. Keys are Hanon's spelling (G♭ major, not F♯).
// The arpeggios have 13 notes a run, grouped by octave of the triad (root, third, fifth).

export const HANON_EDITION =
  'Charles-Louis Hanon, The Virtuoso Pianist, Nos. 39, 40 and 41. G. Schirmer, New York, n.d. [1900], plate 15538 (IMSLP #91547).';

export interface HanonRuns {
  rightUp: string;
  rightDown: string;
  leftUp: string;
  leftDown: string;
}

export interface HanonScale extends HanonRuns {
  /** Hanon's spelling of the tonic. */
  key: string;
  mode: 'major' | 'harmonicMinor' | 'melodicMinor';
  /** Printed page. */
  page: number;
}

/** A digit taken otherwise than printed; the runs below already hold `used`. */
export interface HanonCorrection {
  key: string;
  mode: HanonScale['mode'];
  run: keyof HanonRuns;
  /** Index in the run, 0 = its first note. */
  index: number;
  note: string;
  printed: number;
  used: number;
  reason: string;
}

export const HANON_CORRECTIONS: readonly HanonCorrection[] = [
  {
    key: 'D',
    mode: 'major',
    run: 'leftDown',
    index: 27,
    note: 'E2',
    printed: 1,
    used: 4,
    reason:
      'Printed 1 on both copies of the plate; the pattern of every other octave and the 5 on the following D need 4.',
  },
];

/** No. 39, in Hanon's order (majors by fourths, each followed by its relative minor twice). */
export const HANON_SCALES: readonly HanonScale[] = [
  {
    key: 'C',
    mode: 'major',
    page: 50,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'A',
    mode: 'harmonicMinor',
    page: 50,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'A',
    mode: 'melodicMinor',
    page: 50,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'F',
    mode: 'major',
    page: 51,
    rightUp: '1234123 1234123 1234123 1234123 4',
    rightDown: '4 3214321 3214321 3214321 3214321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'D',
    mode: 'harmonicMinor',
    page: 51,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'D',
    mode: 'melodicMinor',
    page: 51,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'Bb',
    mode: 'major',
    page: 52,
    rightUp: '2123123 4123123 4123123 4123123 4',
    rightDown: '4 3213214 3213214 3213214 3213212',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'G',
    mode: 'harmonicMinor',
    page: 52,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'G',
    mode: 'melodicMinor',
    page: 52,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'Eb',
    mode: 'major',
    page: 53,
    rightUp: '2123412 3123412 3123412 3123412 3',
    rightDown: '3 2143213 2143213 2143213 2143212',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'C',
    mode: 'harmonicMinor',
    page: 53,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'C',
    mode: 'melodicMinor',
    page: 53,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'Ab',
    mode: 'major',
    page: 54,
    rightUp: '2312312 3412312 3412312 3412312 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'F',
    mode: 'harmonicMinor',
    page: 54,
    rightUp: '1234123 1234123 1234123 1234123 4',
    rightDown: '4 3214321 3214321 3214321 3214321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'F',
    mode: 'melodicMinor',
    page: 54,
    rightUp: '1234123 1234123 1234123 1234123 4',
    rightDown: '4 3214321 3214321 3214321 3214321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'Db',
    mode: 'major',
    page: 55,
    rightUp: '2312341 2312341 2312341 2312341 2',
    rightDown: '2 1432132 1432132 1432132 1432132',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'Bb',
    mode: 'harmonicMinor',
    page: 55,
    rightUp: '2123123 4123123 4123123 4123123 4',
    rightDown: '4 3213214 3213214 3213214 3213212',
    leftUp: '2132143 2132143 2132143 2132143 2',
    leftDown: '2 3412312 3412312 3412312 3412312',
  },
  {
    key: 'Bb',
    mode: 'melodicMinor',
    page: 55,
    rightUp: '2123123 4123123 4123123 4123123 4',
    rightDown: '4 3213214 3213214 3213214 3213212',
    leftUp: '2132143 2132143 2132143 2132143 2',
    leftDown: '2 3412312 3412312 3412312 3412312',
  },
  {
    key: 'Gb',
    mode: 'major',
    page: 56,
    rightUp: '2341231 2341231 2341231 2341231 3',
    rightDown: '3 1321432 1321432 1321432 1321432',
    leftUp: '4321321 4321321 4321321 4321321 2',
    leftDown: '2 1231234 1231234 1231234 1231234',
  },
  {
    key: 'Eb',
    mode: 'harmonicMinor',
    page: 56,
    rightUp: '2123412 3123412 3123412 3123412 3',
    rightDown: '3 2143213 2143213 2143213 2143212',
    leftUp: '2143213 2143213 2143213 2143213 2',
    leftDown: '2 3123412 3123412 3123412 3123412',
  },
  {
    key: 'Eb',
    mode: 'melodicMinor',
    page: 56,
    rightUp: '2123412 3123412 3123412 3123412 3',
    rightDown: '3 2143213 2143213 2143213 2143212',
    leftUp: '2143213 2143213 2143213 2143213 2',
    leftDown: '2 3123412 3123412 3123412 3123412',
  },
  {
    key: 'B',
    mode: 'major',
    page: 57,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '4321432 1321432 1321432 1321432 1',
    leftDown: '1 2341231 2341231 2341231 2341234',
  },
  {
    key: 'G#',
    mode: 'harmonicMinor',
    page: 57,
    rightUp: '2312312 3412312 3412312 3412312 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'G#',
    mode: 'melodicMinor',
    page: 57,
    rightUp: '2312312 3412312 3412312 3412312 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 3123123 4123123 4123123 4123123',
  },
  {
    key: 'E',
    mode: 'major',
    page: 58,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'C#',
    mode: 'harmonicMinor',
    page: 58,
    rightUp: '2312312 3412312 3412312 3412312 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'C#',
    mode: 'melodicMinor',
    page: 58,
    rightUp: '2312341 2312341 2312341 2312341 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '3214321 3214321 3214321 3214321 2',
    leftDown: '2 1234123 1234123 1234123 1234123',
  },
  {
    key: 'A',
    mode: 'major',
    page: 59,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'F#',
    mode: 'harmonicMinor',
    page: 59,
    rightUp: '2312312 3412312 3412312 3412312 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '4321321 4321321 4321321 4321321 2',
    leftDown: '2 1231234 1231234 1231234 1231234',
  },
  {
    key: 'F#',
    mode: 'melodicMinor',
    page: 59,
    rightUp: '2312341 2312341 2312341 2312341 3',
    rightDown: '3 2132143 2132143 2132143 2132132',
    leftUp: '4321321 4321321 4321321 4321321 2',
    leftDown: '2 1231234 1231234 1231234 1231234',
  },
  // leftDown[27] (E2): printed 1, used 4; see HANON_CORRECTIONS.
  {
    key: 'D',
    mode: 'major',
    page: 60,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'B',
    mode: 'harmonicMinor',
    page: 60,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '4321432 1321432 1321432 1321432 1',
    leftDown: '1 2341231 2341231 2341231 2341234',
  },
  {
    key: 'B',
    mode: 'melodicMinor',
    page: 60,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '4321432 1321432 1321432 1321432 1',
    leftDown: '1 2341231 2341231 2341231 2341234',
  },
  {
    key: 'G',
    mode: 'major',
    page: 61,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'E',
    mode: 'harmonicMinor',
    page: 61,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
  {
    key: 'E',
    mode: 'melodicMinor',
    page: 61,
    rightUp: '1231234 1231234 1231234 1231234 5',
    rightDown: '5 4321321 4321321 4321321 4321321',
    leftUp: '5432132 1432132 1432132 1432132 1',
    leftDown: '1 2312341 2312341 2312341 2312345',
  },
];

/** No. 40, the chromatic scale at the octave, from C (right hand C3, left hand C2). */
export const HANON_CHROMATIC: HanonRuns & { page: number } = {
  page: 62,
  rightUp: '131312313131 231312313131 231312313131 231312313134 5',
  rightDown: '5 431313213132 131313213132 131313213132 131313213131',
  leftUp: '431321313132 131321313132 131321313132 131321313132 1',
  leftDown: '1 231313123131 231313123131 231313123131 231313123134',
};

export interface HanonArpeggio extends HanonRuns {
  /** Hanon's spelling of the root. */
  key: string;
  mode: 'major' | 'minor';
  /** Printed page. */
  page: number;
}

/**
 * No. 41, in Hanon's order (majors by fourths, each followed by its relative minor). Digits he did
 * not print are filled by the rules of scripts/scales/hanon/build41.py.
 */
export const HANON_ARPEGGIOS: readonly HanonArpeggio[] = [
  {
    key: 'C',
    mode: 'major',
    page: 65,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'A',
    mode: 'minor',
    page: 65,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'F',
    mode: 'major',
    page: 65,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'D',
    mode: 'minor',
    page: 65,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'Bb',
    mode: 'major',
    page: 65,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '321 321 321 321 2',
    leftDown: '2 123 123 123 123',
  },
  {
    key: 'G',
    mode: 'minor',
    page: 65,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'Eb',
    mode: 'major',
    page: 66,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '314 214 214 214 2',
    leftDown: '2 412 412 412 413',
  },
  {
    key: 'C',
    mode: 'minor',
    page: 66,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'Ab',
    mode: 'major',
    page: 66,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '314 214 214 214 2',
    leftDown: '2 412 412 412 413',
  },
  {
    key: 'F',
    mode: 'minor',
    page: 66,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'Db',
    mode: 'major',
    page: 66,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '214 214 214 214 2',
    leftDown: '2 412 412 412 412',
  },
  {
    key: 'Bb',
    mode: 'minor',
    page: 66,
    rightUp: '231 231 231 231 3',
    rightDown: '3 132 132 132 132',
    leftUp: '321 321 321 321 2',
    leftDown: '2 123 123 123 123',
  },
  {
    key: 'Gb',
    mode: 'major',
    page: 67,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '532 132 132 132 1',
    leftDown: '1 231 231 231 235',
  },
  {
    key: 'Eb',
    mode: 'minor',
    page: 67,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'B',
    mode: 'major',
    page: 67,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '532 132 132 132 1',
    leftDown: '1 231 231 231 235',
  },
  {
    key: 'G#',
    mode: 'minor',
    page: 67,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '314 214 214 214 2',
    leftDown: '2 412 412 412 413',
  },
  {
    key: 'E',
    mode: 'major',
    page: 67,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '532 132 132 132 1',
    leftDown: '1 231 231 231 235',
  },
  {
    key: 'C#',
    mode: 'minor',
    page: 67,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '314 214 214 214 2',
    leftDown: '2 412 412 412 413',
  },
  {
    key: 'A',
    mode: 'major',
    page: 68,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '532 132 132 132 1',
    leftDown: '1 231 231 231 235',
  },
  {
    key: 'F#',
    mode: 'minor',
    page: 68,
    rightUp: '212 412 412 412 4',
    rightDown: '4 214 214 214 212',
    leftUp: '314 214 214 214 2',
    leftDown: '2 412 412 412 413',
  },
  {
    key: 'D',
    mode: 'major',
    page: 68,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '532 132 132 132 1',
    leftDown: '1 231 231 231 235',
  },
  {
    key: 'B',
    mode: 'minor',
    page: 68,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'G',
    mode: 'major',
    page: 68,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
  {
    key: 'E',
    mode: 'minor',
    page: 68,
    rightUp: '123 123 123 123 5',
    rightDown: '5 321 321 321 321',
    leftUp: '542 142 142 142 1',
    leftDown: '1 241 241 241 245',
  },
];
