// Sight-reading on Read (docs/READING.md, "Sight-reading (R3)"): short fragments of music never
// seen before, generated by rules from a level, a seed and a generator version, so the stored seed
// and version give the same fragment again. The MusicXML Verovio draws is sightXml.ts's.
//
// The algorithm, for one fragment (every choice from one seeded rng, in this order):
//
// 1. **Key and meter** of the level, at random (4/4 more often than 3/4 and 2/4).
// 2. **Phrases.** Four bars are one phrase; eight are two, the first ending on a half cadence (V)
//    and the second, which often begins as the first did (a parallel period), on I.
// 3. **Harmony**, bar by bar, from phrase patterns of I, IV and V (ii and vi from F6; i, iv, V
//    and VI in minor): the first bar is I, the bar before a cadence ends on V (with a
//    pre-dominant or I on its first half from F5), the last bar is I.
// 4. **Rhythm** of the melody, cell by cell from the cells of the level's rhythm levels (R1-R5),
//    halves only on strong beats; the third bar often takes the first bar's rhythm; a half cadence
//    ends on a long note, and the last bar is one note that fills it.
// 5. **The left hand** by the level's texture: rests while the right hand plays alone, the melody
//    itself (F2), held roots (F4), a bass note per half bar (F5), fifths and sixths or a walking
//    line (F6-F7), block, broken and Alberti chords (F8); in a five-finger position around the
//    tonic an octave or two below the right hand's.
// 6. **The melody**, a constrained random walk with backtracking in a hand position (five fingers
//    until F4, stretched to a sixth from F5, shifting between the phrases in F7-F8): steps mostly,
//    leaps limited by level and only between chord tones, a leap turned back by step; every strong
//    beat and long note a chord tone, every other note a passing or neighbour note by step; the
//    leading tone rising to the tonic; no melodic tritone or augmented second; above the left hand,
//    never in parallel fifths or octaves with its bass; shaped towards a high point and down to a
//    cadence on the tonic (by step until F4). F3 passes this one line between the hands.
// 7. **Accidentals** (F7-F8): some lower neighbours a whole step below are raised a semitone.
// 8. **Fingering**: only each hand's first note (or chord) is fingered, from its position.
//
// An attempt that cannot be completed (the walk runs out of room) starts over from step 3 with the
// rng as it is, so every seed gives a fragment; tests check how few attempts it takes.

import { midiOf } from './musicxml.ts';
import { isBlack } from './note.ts';
import type { Rng } from './random.ts';
import { seededRng } from './random.ts';
import { CELLS } from './rhythmCells.ts';
import { keySignature, scaleDegree, tonicPitch } from './keys.ts';
import { TICKS_PER_QUARTER, type Hand, type SpelledPitch } from './score.ts';

import {
  barTicks,
  beatsOf,
  getSightLevel,
  levelCells,
  SIGHT_GENERATOR_VERSION,
  SIGHT_GENERATOR_VERSIONS,
  type Mode,
  type SightKey,
  type SightLevel,
  type SightLevelId,
  type SightMeter,
  type Texture,
} from './sightLevels.ts';

// --- The fragment ----------------------------------------------------------------------------

/** One written note of a fragment. */
export interface SightNote {
  hand: Hand;
  pitch: SpelledPitch;
  midi: number;
  /** Ticks (`TICKS_PER_QUARTER` to a quarter) from the start of the fragment. */
  onset: number;
  duration: number;
  /** Tied to the next note of its hand (the same key). */
  tieStart: boolean;
  /** Continues a tie: sounds on, is not pressed. */
  tieStop: boolean;
  /** Printed for each hand's first note (or chord) only. */
  finger: number | null;
  /** The rhythm cell it belongs to (`q`, `~h`, `e-ss`…), or `final` for a last bar's note. */
  cell: string;
}

export type Chord = 'I' | 'ii' | 'IV' | 'V' | 'vi';

/** A chord and where it starts in its bar, in beats. */
export interface HarmonySlot {
  beat: number;
  chord: Chord;
}

export interface SightFragment {
  level: SightLevelId;
  seed: number;
  version: number;
  key: SightKey;
  /** The key signature: sharps (+) or flats (−). */
  fifths: number;
  meter: SightMeter;
  bars: number;
  /** Both hands, by onset, then the left hand first, then pitch. */
  notes: SightNote[];
  /** Per bar, the chords under it. */
  harmony: HarmonySlot[][];
  /** The bar each phrase starts at (0 and, in eight bars, 4). */
  phrases: number[];
  /** Attempts it took (1 when the first worked); for the tests. */
  attempts: number;
}

// --- Helpers ---------------------------------------------------------------------------------

const mod7 = (n: number) => ((n % 7) + 7) % 7;

function pick<T>(rng: Rng, options: readonly (readonly [T, number])[]): T {
  const total = options.reduce((sum, [, w]) => sum + Math.max(0, w), 0);
  let r = rng() * total;
  for (const [value, w] of options) {
    if (w <= 0) continue;
    r -= w;
    if (r < 0) return value;
  }
  return options.findLast(([, w]) => w > 0)?.[0] ?? options[0]![0];
}

const chance = (rng: Rng, p: number) => rng() < p;

/** The chord's root, as a scale degree from 0 (the tonic). */
const ROOT: Record<Chord, number> = { I: 0, ii: 1, IV: 3, V: 4, vi: 5 };

function isChordTone(chord: Chord, degree: number): boolean {
  const offset = mod7(degree - ROOT[chord]);
  return offset === 0 || offset === 2 || offset === 4;
}

/** In minor, the seventh degree is raised (the leading tone) under V, and only there. */
function raised(k: SightKey, chord: Chord, degree: number): boolean {
  return k.mode === 'minor' && chord === 'V' && mod7(degree) === 6;
}

/**
 * The octave the tonic of each hand's position is in: the right hand's from middle C up to the B
 * above; the left hand's an octave or two below, from F2 up to E3 so that its position lies on the
 * bass staff, and for chords from G2 up to F♯3 (a close triad lower sounds thick).
 */
export function tonicOctave(k: SightKey, hand: Hand, texture: Texture): number {
  if (hand === 'right') return 4;
  const top = texture === 'chords' ? 55 : 53;
  return midiOf(tonicPitch(k.tonic, 3)) < top ? 3 : 2;
}

interface Speller {
  pitch: (hand: Hand, degree: number, chord: Chord) => SpelledPitch;
  midi: (hand: Hand, degree: number, chord: Chord) => number;
}

function speller(k: SightKey, texture: Texture): Speller {
  const type = k.mode === 'major' ? 'major' : 'naturalMinor';
  const cache = new Map<string, SpelledPitch>();
  const pitch = (hand: Hand, degree: number, chord: Chord): SpelledPitch => {
    const up = raised(k, chord, degree);
    const id = `${hand}:${degree}:${up}`;
    let p = cache.get(id);
    if (!p) {
      const base = scaleDegree(type, tonicPitch(k.tonic, tonicOctave(k, hand, texture)), degree);
      p = up ? { ...base, alter: base.alter + 1 } : base;
      cache.set(id, p);
    }
    return p;
  };
  return { pitch, midi: (hand, degree, chord) => midiOf(pitch(hand, degree, chord)) };
}

// --- Rhythm ----------------------------------------------------------------------------------

/** A note or rest of a bar's rhythm. */
interface Beat {
  /** Ticks from the start of the bar. */
  start: number;
  ticks: number;
  rest: boolean;
  /** Tied from the note before (the same pitch, not pressed). */
  tied: boolean;
  cell: string;
}

const FINAL = 'final';

function beatsOfCells(cells: readonly string[]): Beat[] {
  const out: Beat[] = [];
  let at = 0;
  for (const key of cells) {
    const def = CELLS[key === FINAL ? 'hd' : key]!;
    for (const n of def.notes) {
      out.push({ start: at, ticks: n.ticks, rest: n.rest, tied: n.tied, cell: key });
      at += n.ticks;
    }
  }
  return out;
}

/** The melody's cells and how often each is drawn (rests, ties and wholes are placed by rule). */
const MELODY_WEIGHTS: Readonly<Record<string, number>> = {
  q: 10,
  h: 3.5,
  ee: 5,
  'qd-e': 2.5,
  hd: 1.2,
  'e-ss': 1.2,
  'ss-e': 1.2,
  ssss: 0.8,
  'ed-s': 1.2,
};

const beatLength = (cell: string) => CELLS[cell]!.beats;

/** Where a cell may start in the bar: a half or a dotted rhythm on a strong beat. */
function fitsBeat(cell: string, meter: SightMeter, at: number): boolean {
  const beats = beatsOf(meter);
  if (at + beatLength(cell) > beats) return false;
  if (cell === 'h' || cell === 'qd-e') return meter === '3/4' ? at <= 1 : at % 2 === 0;
  if (cell === 'hd') return at === 0;
  return true;
}

function drawBar(level: SightLevel, meter: SightMeter, rng: Rng): string[] {
  const allowed = levelCells(level).filter((c) => MELODY_WEIGHTS[c] !== undefined);
  for (let attempt = 0; attempt < 12; attempt++) {
    const cells: string[] = [];
    let at = 0;
    while (at < beatsOf(meter)) {
      const options = allowed
        .filter((c) => fitsBeat(c, meter, at))
        .map((c) => [c, MELODY_WEIGHTS[c]!] as const);
      const cell = pick(rng, options);
      cells.push(cell);
      at += beatLength(cell);
    }
    const eighths = cells.filter((c) => c === 'ee').length;
    const sixteenths = cells.filter((c) => c.includes('s')).length;
    const notes = beatsOfCells(cells).length;
    // Not too busy, and something moving: a bar is not one held note unless it is short.
    if (eighths <= 2 && sixteenths <= 1 && (notes >= 2 || meter === '2/4')) return cells;
  }
  return Array.from({ length: beatsOf(meter) }, () => 'q');
}

/** The last bar: one note that fills it (a whole, a dotted half, a half). */
function finalBar(meter: SightMeter): string[] {
  return meter === '4/4' ? ['w'] : meter === '3/4' ? [FINAL] : ['h'];
}

/** The bar of a half cadence ends on a long note. */
function halfCadenceBar(level: SightLevel, meter: SightMeter, rng: Rng): string[] {
  const cells = levelCells(level);
  if (meter === '2/4') return ['h'];
  if (meter === '3/4')
    return pick(rng, [
      [['hd'], cells.includes('hd') ? 2 : 0],
      [['q', 'h'], 2],
    ]);
  return pick(rng, [
    [['q', 'q', 'h'], 3],
    [['h', 'h'], 2],
    [['ee', 'q', 'h'], cells.includes('ee') ? 1.5 : 0],
    [['qd-e', 'h'], cells.includes('qd-e') ? 1.5 : 0],
    [['w'], 0.5],
  ]);
}

interface Plan {
  meter: SightMeter;
  bars: number;
  /** The bar each phrase starts at. */
  phrases: number[];
  /** Eight bars whose second phrase begins as the first (bars 5-6 as 1-2). */
  parallel: boolean;
}

/** The melody's rhythm, bar by bar, as cells. */
function melodyRhythm(level: SightLevel, plan: Plan, rng: Rng): string[][] {
  const { meter, bars } = plan;
  const out: string[][] = [];
  for (let b = 0; b < bars; b++) {
    if (b === bars - 1) out.push(finalBar(meter));
    else if (bars === 8 && b === 3) out.push(halfCadenceBar(level, meter, rng));
    else if ((b === 2 || b === 6) && chance(rng, 0.45)) out.push([...out[b - 2]!]);
    else if (plan.parallel && (b === 4 || b === 5)) out.push([...out[b - 4]!]);
    else out.push(drawBar(level, meter, rng));
  }
  // A breath in the phrase: the second bar may end with a quarter rest.
  const breath = level.texture === 'turns' || level.texture === 'right' ? 0.3 : 0.15;
  for (const b of bars === 8 ? [1, 5] : [1]) {
    const cells = out[b]!;
    if (meter !== '2/4' && cells.at(-1) === 'q' && cells.length >= 2 && chance(rng, breath)) {
      cells[cells.length - 1] = 'qr';
      if (plan.parallel && b === 1) out[5]![out[5]!.length - 1] = 'qr';
    }
  }
  // R4: a note tied over the barline into the downbeat (never into the last bar or a phrase).
  if (level.ties) {
    let ties = 0;
    for (let b = 1; b < bars - 1 && ties < 2; b++) {
      if (plan.phrases.includes(b)) continue;
      const before = out[b - 1]!.at(-1);
      const first = out[b]![0]!;
      if (before === 'qr' || before === undefined) continue;
      if (!['q', 'h', 'ee', 'qd-e'].includes(first)) continue;
      if (plan.parallel && (b === 5 || b === 1)) continue;
      if (chance(rng, 0.2)) {
        out[b]![0] = `~${first}`;
        ties++;
      }
    }
  }
  return out;
}

// --- Harmony ---------------------------------------------------------------------------------

type BarHarmony = HarmonySlot[];

const one = (chord: Chord): BarHarmony => [{ beat: 0, chord }];

/** The second half of the bar: beat 3 in 4/4 and 3/4, beat 2 in 2/4. */
const halfBeat = (meter: SightMeter) => (meter === '2/4' ? 1 : 2);

function two(meter: SightMeter, a: Chord, b: Chord): BarHarmony {
  return [
    { beat: 0, chord: a },
    { beat: halfBeat(meter), chord: b },
  ];
}

/**
 * A phrase's chords: I first; then the bar after, a bar leading to the cadence, and the cadence
 * (V for a half cadence; V then I for the last phrase).
 */
function phraseHarmony(
  level: SightLevel,
  meter: SightMeter,
  mode: Mode,
  rng: Rng,
  ending: 'half' | 'full',
): BarHarmony[] {
  // ii is diminished in minor: iv and VI only.
  const ii = level.secondary && mode === 'major';
  const second = level.secondary
    ? pick<Chord>(rng, [
        ['IV', 3],
        ['V', 2],
        ['vi', 2],
        ['ii', ii ? 1 : 0],
        ['I', 1],
      ])
    : pick<Chord>(rng, [
        ['IV', 4.5],
        ['V', 3],
        ['I', 2.5],
      ]);
  const twoChords = level.extended; // F5 up: two chords in a bar, as a cadence wants them
  if (ending === 'half') {
    const third = pick<Chord>(rng, [
      ['I', second === 'I' ? 0 : 3],
      ['IV', second === 'IV' ? 0 : 3],
      ['ii', ii && second !== 'V' && second !== 'ii' ? 1.5 : 0],
      ['vi', level.secondary && second === 'I' ? 1 : 0],
    ]);
    return [one('I'), one(second), one(third), one('V')];
  }
  const options: (readonly [BarHarmony, number])[] = [[one('V'), 3]];
  if (twoChords) {
    if (second !== 'V') options.push([two(meter, 'IV', 'V'), 2.5]);
    options.push([two(meter, 'I', 'V'), second === 'I' ? 0 : 1.5]);
    if (ii && second !== 'V') options.push([two(meter, 'ii', 'V'), 2]);
  }
  return [one('I'), one(second), pick(rng, options), one('I')];
}

function harmonyPlan(level: SightLevel, plan: Plan, mode: Mode, rng: Rng): BarHarmony[] {
  if (plan.bars === 4) return phraseHarmony(level, plan.meter, mode, rng, 'full');
  const first = phraseHarmony(level, plan.meter, mode, rng, 'half');
  const second = phraseHarmony(level, plan.meter, mode, rng, 'full');
  if (plan.parallel) {
    second[0] = first[0]!;
    second[1] = first[1]!;
  }
  return [...first, ...second];
}

function chordAt(harmony: BarHarmony, beat: number): Chord {
  return harmony.findLast((s) => s.beat <= beat + 1e-9)!.chord;
}

// --- The left hand ---------------------------------------------------------------------------

/** One left-hand note or chord, in degrees from the left hand's tonic. */
interface LeftEvent {
  bar: number;
  start: number;
  ticks: number;
  /** Ascending; empty for a rest. */
  degrees: number[];
  chord: Chord;
  cell: string;
  /** Not a chord tone: a passing or neighbour note of a walking line. */
  passing?: boolean;
}

/** The left hand's position (degrees from its tonic): five fingers, from F6 a sixth and below. */
const leftWindow = (level: SightLevel): [number, number] =>
  level.texture === 'moving' || level.texture === 'chords' ? [-1, 5] : [0, 4];

/** Fifths and sixths per chord, in the left hand's position (F6-F7). */
const DYADS: Record<Chord, number[]> = {
  I: [0, 4],
  ii: [1, 5],
  IV: [0, 5],
  V: [-1, 4],
  vi: [0, 5],
};

/** Close-position triads that move by the smallest steps: I, IV6/4, V6, ii, vi6 (F8). */
const TRIADS: Record<Chord, number[]> = {
  I: [0, 2, 4],
  ii: [1, 3, 5],
  IV: [0, 3, 5],
  V: [-1, 1, 4],
  vi: [0, 2, 5],
};

/** The chord's root in the left hand's position (its fifth below in V: G of G-B-D is the top). */
function rootIn(chord: Chord, [lo, hi]: [number, number]): number {
  const r = ROOT[chord];
  return r > hi ? r - 7 : r < lo ? r + 7 : r;
}

/** Chord tones of `chord` within the window, low to high. */
function chordTonesIn(chord: Chord, [lo, hi]: [number, number]): number[] {
  const out: number[] = [];
  for (let d = lo; d <= hi; d++) if (isChordTone(chord, d)) out.push(d);
  return out;
}

/** The lengths of a bar split at its half: 2+2, 2+1, 1+1 beats. */
function halves(meter: SightMeter): [number, number] {
  return meter === '4/4' ? [2, 2] : meter === '3/4' ? [2, 1] : [1, 1];
}

const beatCell = (beats: number) =>
  beats === 4 ? 'w' : beats === 3 ? 'hd' : beats === 2 ? 'h' : 'q';

type LeftPattern = 'root' | 'halves' | 'dyad' | 'dyads' | 'line' | 'block' | 'blockHalf';
type ChordPattern = 'block' | 'blockHalf' | 'alberti' | 'broken';

/** A bar of the left hand, before walking lines (which need the next bar's bass) are filled. */
interface LeftBar {
  pattern: LeftPattern | ChordPattern;
  events: LeftEvent[];
}

function leftBars(
  level: SightLevel,
  plan: Plan,
  harmony: readonly BarHarmony[],
  k: SightKey,
  spell: Speller,
  rng: Rng,
): LeftEvent[] | null {
  const { meter, bars } = plan;
  const Q = TICKS_PER_QUARTER;
  const window = leftWindow(level);
  const beats = beatsOf(meter);
  const [h1, h2] = halves(meter);
  const out: LeftBar[] = [];
  const ev = (
    bar: number,
    startBeat: number,
    lengthBeats: number,
    degrees: number[],
    chord: Chord,
    cell = beatCell(lengthBeats),
  ): LeftEvent => ({
    bar,
    start: startBeat * Q,
    ticks: lengthBeats * Q,
    degrees,
    chord,
    cell,
  });
  const last = bars - 1;
  const chordPattern: ChordPattern | null =
    level.texture === 'chords'
      ? pick<ChordPattern>(rng, [
          ['block', 1],
          ['blockHalf', meter === '2/4' ? 0.5 : 1.5],
          ['alberti', meter === '3/4' ? 0 : 2],
          ['broken', 1.5],
        ])
      : null;
  // F6-F7: a pattern per phrase, the bar before the cadence sometimes walking.
  const phrasePatterns = plan.phrases.map(() =>
    pick<LeftPattern>(rng, [
      ['dyads', 3],
      ['line', 2],
      ['halves', 1],
    ]),
  );

  for (let b = 0; b < bars; b++) {
    const slots = harmony[b]!;
    const first = slots[0]!.chord;
    const at = (beat: number) => chordAt(slots, beat);
    const phrase = plan.phrases.findLastIndex((p) => p <= b);
    const endOfPhrase = b === last || (bars === 8 && b === 3);
    let bar: LeftBar;
    switch (level.texture) {
      case 'right':
      case 'left':
      case 'turns':
        bar = { pattern: 'root', events: [] };
        break;
      case 'held':
        bar = { pattern: 'root', events: [ev(b, 0, beats, [rootIn(first, window)], first)] };
        break;
      case 'halves': {
        if (endOfPhrase || (slots.length === 1 && chance(rng, 0.15))) {
          bar = { pattern: 'root', events: [ev(b, 0, beats, [rootIn(first, window)], first)] };
          break;
        }
        const a = rootIn(first, window);
        const second = at(h1);
        let bDeg: number;
        if (slots.length > 1) bDeg = rootIn(second, window);
        else {
          const others = chordTonesIn(first, window).filter((d) => d !== a);
          bDeg = pick(
            rng,
            others.map((d) => [d, mod7(d - ROOT[first]) === 4 ? 3 : 1.5] as const),
          );
        }
        bar = {
          pattern: 'halves',
          events: [ev(b, 0, h1, [a], first), ev(b, h1, h2, [bDeg], second)],
        };
        break;
      }
      case 'moving': {
        if (endOfPhrase) {
          const dyad = chance(rng, 0.6);
          bar = {
            pattern: dyad ? 'dyad' : 'root',
            events: [ev(b, 0, beats, dyad ? DYADS[first] : [rootIn(first, window)], first)],
          };
          break;
        }
        let pattern = phrasePatterns[phrase]!;
        if (b % 4 === 2 && chance(rng, 0.35)) pattern = 'line';
        if (pattern === 'line') {
          bar = { pattern, events: [] };
        } else if (pattern === 'dyads') {
          const second = at(h1);
          const split = slots.length > 1 || chance(rng, 0.7);
          bar = {
            pattern,
            events: split
              ? [ev(b, 0, h1, DYADS[first], first), ev(b, h1, h2, DYADS[second], second)]
              : [ev(b, 0, beats, DYADS[first], first)],
          };
        } else {
          const second = at(h1);
          const a = rootIn(first, window);
          const others = chordTonesIn(first, window).filter((d) => d !== a);
          const bDeg =
            slots.length > 1
              ? rootIn(second, window)
              : pick(
                  rng,
                  others.map((d) => [d, 1] as const),
                );
          bar = { pattern, events: [ev(b, 0, h1, [a], first), ev(b, h1, h2, [bDeg], second)] };
        }
        break;
      }
      case 'chords': {
        const pattern: ChordPattern = b === last ? 'block' : chordPattern!;
        bar = { pattern, events: chordBar(b, pattern, slots, meter) };
        break;
      }
    }
    out.push(bar);
  }
  // The second phrase of a parallel period begins as the first did.
  if (plan.parallel && level.texture !== 'chords') {
    for (const b of [4, 5]) {
      const from = out[b - 4]!;
      out[b] = { pattern: from.pattern, events: from.events.map((e) => ({ ...e, bar: b })) };
    }
  }
  // Walking lines, now that every bar's first bass note is known.
  for (let b = 0; b < bars; b++) {
    if (out[b]!.pattern !== 'line') continue;
    const next = out[b + 1];
    if (!next) return null;
    const target =
      next.pattern === 'line'
        ? rootIn(harmony[b + 1]![0]!.chord, window)
        : next.events[0]!.degrees[0]!;
    const line = walkingLine(b, harmony[b]!, meter, target, window, k, spell, rng);
    if (!line) return null;
    out[b] = { pattern: 'line', events: line };
  }
  return out.flatMap((bar) => bar.events);
}

/** A bar of chords (F8): block, on each half bar, Alberti eighths or broken in quarters. */
function chordBar(
  b: number,
  pattern: ChordPattern,
  slots: BarHarmony,
  meter: SightMeter,
): LeftEvent[] {
  const Q = TICKS_PER_QUARTER;
  const beats = beatsOf(meter);
  const at = (beat: number) => chordAt(slots, beat);
  const events: LeftEvent[] = [];
  const add = (start: number, ticks: number, degrees: number[], chord: Chord, cell: string) =>
    events.push({ bar: b, start, ticks, degrees, chord, cell });
  if (pattern === 'block') {
    if (slots.length === 1)
      add(0, beats * Q, TRIADS[slots[0]!.chord], slots[0]!.chord, beatCell(beats));
    else {
      const [h1, h2] = halves(meter);
      add(0, h1 * Q, TRIADS[at(0)], at(0), beatCell(h1));
      add(h1 * Q, h2 * Q, TRIADS[at(h1)], at(h1), beatCell(h2));
    }
  } else if (pattern === 'blockHalf') {
    if (meter === '3/4') {
      // A waltz: the bass on the beat, the chord's upper notes on two and three.
      for (let beat = 0; beat < 3; beat++) {
        const chord = at(beat);
        const [low, ...upper] = TRIADS[chord];
        add(beat * Q, Q, beat === 0 ? [low!] : upper, chord, 'q');
      }
    } else {
      const [h1, h2] = halves(meter);
      add(0, h1 * Q, TRIADS[at(0)], at(0), beatCell(h1));
      add(h1 * Q, h2 * Q, TRIADS[at(h1)], at(h1), beatCell(h2));
    }
  } else if (pattern === 'alberti') {
    // Low, high, middle, high in eighths, two to the beat.
    for (let e = 0; e < beats * 2; e++) {
      const chord = at(Math.floor(e / 2));
      const [low, mid, high] = TRIADS[chord] as [number, number, number];
      const degree = e % 4 === 0 ? low : e % 4 === 2 ? mid : high;
      add((e * Q) / 2, Q / 2, [degree], chord, 'ee');
    }
  } else {
    // Broken in quarters: up the chord and back (4/4), up it (3/4), low and high (2/4).
    const order = meter === '4/4' ? [0, 1, 2, 1] : meter === '3/4' ? [0, 1, 2] : [0, 2];
    order.forEach((i, beat) => {
      const chord = at(beat);
      add(beat * Q, Q, [TRIADS[chord][i]!], chord, 'q');
    });
  }
  return events;
}

const STEP_SEMITONES: Readonly<Record<number, readonly number[]>> = {
  0: [0],
  1: [1, 2],
  2: [3, 4],
  3: [5],
  4: [7],
  5: [8, 9],
  6: [10, 11],
  7: [12],
};

/** Whether a melodic interval sounds as it should: no augmented second, tritone or augmented fifth. */
function singable(steps: number, semitones: number): boolean {
  return STEP_SEMITONES[Math.abs(steps)]?.includes(Math.abs(semitones)) ?? false;
}

/**
 * A walking bass in quarters from the bar's root to a step or third from `target`, the next bar's
 * first bass note: chord tones on the strong beats, passing and neighbour notes by step between.
 */
function walkingLine(
  bar: number,
  slots: BarHarmony,
  meter: SightMeter,
  target: number,
  window: [number, number],
  k: SightKey,
  spell: Speller,
  rng: Rng,
): LeftEvent[] | null {
  const beats = beatsOf(meter);
  const chords = Array.from({ length: beats }, (_, beat) => chordAt(slots, beat));
  const strong = (beat: number) =>
    beat === 0 || (meter === '4/4' && beat === 2) || slots.some((s) => s.beat === beat);
  const midi = (degree: number, beat: number) => spell.midi('left', degree, chords[beat]!);
  const lines: { degrees: number[]; weight: number }[] = [];
  const start = rootIn(chords[0]!, window);
  const walk = (degrees: number[]) => {
    const beat = degrees.length;
    if (beat === beats) {
      const lastDeg = degrees.at(-1)!;
      const gap = target - lastDeg;
      if (gap === 0 || Math.abs(gap) > 2) return;
      if (Math.abs(gap) === 2 && !isChordTone(chords[beats - 1]!, lastDeg)) return;
      const moves = degrees.slice(1).map((d, i) => Math.abs(d - degrees[i]!));
      const steps = moves.filter((m) => m === 1).length;
      lines.push({ degrees, weight: 1 + steps * 2 });
      return;
    }
    const prev = degrees.at(-1)!;
    for (let d = window[0]; d <= window[1]; d++) {
      const iv = d - prev;
      if (iv === 0 || Math.abs(iv) > 2) continue;
      const chord = chords[beat]!;
      const tone = isChordTone(chord, d);
      if (strong(beat) && !tone) continue;
      if (!tone && Math.abs(iv) !== 1) continue;
      if (k.mode === 'minor' && mod7(d) === 6 && chord !== 'V') continue;
      if (!singable(iv, midi(d, beat) - midi(prev, beat - 1))) continue;
      // A note off the chord moves on by step (checked when the next is chosen).
      const prevTone = isChordTone(chords[beat - 1]!, prev);
      if (!prevTone && Math.abs(iv) !== 1) continue;
      walk([...degrees, d]);
    }
  };
  walk([start]);
  if (lines.length === 0) return null;
  const chosen = pick(
    rng,
    lines.map((l) => [l.degrees, l.weight] as const),
  );
  // The last note must lead to the target by step when it is not a chord tone.
  return chosen.map((degree, beat) => ({
    bar,
    start: beat * TICKS_PER_QUARTER,
    ticks: TICKS_PER_QUARTER,
    degrees: [degree],
    chord: chords[beat]!,
    cell: 'q',
    passing: !isChordTone(chords[beat]!, degree),
  }));
}

// --- The melody ------------------------------------------------------------------------------

/** A note of the melody to choose a pitch for. */
interface Slot {
  bar: number;
  /** Ticks from the start of the fragment. */
  onset: number;
  ticks: number;
  /** On a strong beat (the downbeat, beat 3 of 4/4, a chord change) or long (a half or more). */
  strong: boolean;
  chord: Chord;
  /** Tied from the note before: its pitch. */
  tied: boolean;
  phrase: number;
  /** The first note of its phrase, and the last. */
  first: boolean;
  last: boolean;
  /** The last note of the fragment: the tonic. */
  final: boolean;
  /** Where it falls in its phrase, 0-1 (for the contour). */
  at: number;
  cell: string;
  /** The notes of the left hand that sound with it: their keys, and those struck with it. */
  under: number;
  struck: { midi: number; passing: boolean }[];
  /** The bass struck with it, for parallels; null when the bass does not move with it. */
  bass: number | null;
}

interface Position {
  lo: number;
  hi: number;
}

/** The right hand's range when it moves: G3 to A5, two ledger lines either side of the staff. */
const RIGHT_LOWEST = 55;
const RIGHT_HIGHEST = 81;

/**
 * The right hand's position per phrase (degrees from its tonic): a five-finger position on the
 * tonic until F4; from F5 stretched a step (the leading tone below or the sixth above); in F7-F8 the
 * second phrase may move up an octave or to the dominant's position.
 */
function positions(level: SightLevel, plan: Plan, spell: Speller, rng: Rng): Position[] {
  const base: Position = level.extended
    ? pick<Position>(rng, [
        [{ lo: 0, hi: 4 }, 1],
        [{ lo: -1, hi: 4 }, 1.5],
        [{ lo: 0, hi: 5 }, 1.5],
      ])
    : { lo: 0, hi: 4 };
  if (plan.phrases.length === 1) return [base];
  if (!level.shifts || !chance(rng, 0.6)) return [base, base];
  // Within the treble staff and two ledger lines either way: G3 to A5.
  const fits = (p: Position) =>
    spell.midi('right', p.lo, 'I') >= RIGHT_LOWEST &&
    spell.midi('right', p.hi, 'I') <= RIGHT_HIGHEST;
  const options: [Position, number][] = [
    [{ lo: base.lo + 7, hi: base.hi + 7 }, plan.parallel ? 3 : 1],
    [{ lo: 4, hi: 8 }, 1.5],
    [{ lo: 3, hi: 8 }, 1],
  ];
  const shifted = pick(
    rng,
    options.map(([p, w]) => [p, fits(p) ? w : 0] as const),
  );
  if (!fits(shifted)) return [base, base];
  return chance(rng, 0.5) || plan.parallel ? [base, shifted] : [shifted, base];
}

interface MelodyContext {
  level: SightLevel;
  plan: Plan;
  k: SightKey;
  spell: Speller;
  /** The hand playing each bar (F2: the left; F3: by turns). */
  hands: Hand[];
  windows: Position[];
  slots: Slot[];
  /** Per phrase: where it peaks (0-1) and how high, and where it ends. */
  contour: ReturnType<typeof contourOf>[];
  rng: Rng;
  budget: number;
}

const INTERVAL_WEIGHT = [0.6, 6, 3, 1.3, 1, 0.5, 0.3, 0.3];

/**
 * Draws the phrase's contour: from its first note up to a high point somewhere past a third of it
 * and down to the cadence; a phrase that starts at the top first dips to the bottom of the hand.
 */
function contourOf(window: Position, ending: 'half' | 'full', rng: Rng) {
  const tonics = [0, 7, -7].filter((d) => d >= window.lo && d <= window.hi);
  const end =
    ending === 'full'
      ? pick(
          rng,
          tonics.map((d) => [d, 1] as const),
        )
      : pick(
          rng,
          [1, 4, 8, -3]
            .filter((d) => d >= window.lo && d <= window.hi)
            .map((d) => [d, mod7(d) === 1 ? 2 : 1] as const),
        );
  const peak = window.hi - (chance(rng, 0.4) ? 1 : 0);
  const valley = window.lo + (chance(rng, 0.5) ? 1 : 0);
  return { peakAt: 0.35 + 0.4 * rng(), peak, valley, end };
}

function target(c: MelodyContext['contour'][number], start: number, at: number): number {
  const points: [number, number][] =
    start >= c.peak - 1
      ? [
          [0, start],
          [0.3, c.valley],
          [Math.max(0.6, c.peakAt), c.peak],
          [1, c.end],
        ]
      : [
          [0, start],
          [c.peakAt, c.peak],
          [1, c.end],
        ];
  const k = points.findIndex(([x]) => x >= at);
  if (k <= 0) return start;
  const [x0, y0] = points[k - 1]!;
  const [x1, y1] = points[k]!;
  return y0 + ((y1 - y0) * (at - x0)) / (x1 - x0);
}

function solveMelody(ctx: MelodyContext, fixed: ReadonlyMap<number, number>): number[] | null {
  const { slots, level, k, spell, windows, hands } = ctx;
  const chosen: number[] = [];
  const midis: number[] = [];
  const handOf = (i: number) => hands[slots[i]!.bar]!;
  const midiOfSlot = (i: number, d: number) => spell.midi(handOf(i), d, slots[i]!.chord);
  const steps = level.maxLeap;
  // Parallel fifths and octaves: the last slot struck together with the bass.
  const lastWithBass = (i: number) => {
    for (let j = i - 1; j >= 0; j--) if (slots[j]!.bass !== null) return j;
    return -1;
  };

  function allowed(i: number, d: number): boolean {
    const s = slots[i]!;
    const w = windows[s.phrase]!;
    if (d < w.lo || d > w.hi) return false;
    const tone = isChordTone(s.chord, d);
    if ((s.strong || s.first || s.last) && !tone) return false;
    if (s.final && mod7(d) !== 0) return false;
    if (k.mode === 'minor' && mod7(d) === 6 && s.chord !== 'V') return false;
    const m = midiOfSlot(i, d);
    // Above the left hand, clear of it.
    if (m <= s.under) return false;
    for (const n of s.struck) {
      if (!tone || n.passing) {
        const ic = (((m - n.midi) % 12) + 12) % 12;
        if (ic === 1 || ic === 11 || (ic === 2 && n.passing)) return false;
      }
    }
    if (i === 0) return true;
    const p = chosen[i - 1]!;
    const pm = midis[i - 1]!;
    const iv = d - p;
    const handChange = handOf(i) !== handOf(i - 1);
    const newPhrase = s.first && s.phrase > 0;
    if (s.tied) return iv === 0;
    const limit = newPhrase && windows[s.phrase] !== windows[s.phrase - 1] ? 7 : steps;
    if (Math.abs(iv) > limit) return false;
    // The line passes to the other hand an octave or two away: judged by its degrees.
    if (!handChange && !singable(iv, m - pm)) return false;
    const ps = slots[i - 1]!;
    const pTone = isChordTone(ps.chord, p);
    // Off the chord: by step in and out.
    if (!tone && Math.abs(iv) !== 1) return false;
    if (!pTone && Math.abs(iv) !== 1 && !ps.tied) return false;
    // A repeated note only between notes of a beat or more.
    if (iv === 0 && (s.ticks < TICKS_PER_QUARTER || ps.ticks < TICKS_PER_QUARTER)) return false;
    if (i >= 2) {
      const pp = chosen[i - 2]!;
      const prevIv = p - pp;
      // Three of one pitch in a row.
      if (iv === 0 && prevIv === 0) return false;
      // Two notes off the chord in a row only as a run in one direction.
      if (!tone && !pTone && Math.sign(iv) !== Math.sign(prevIv)) return false;
      // After a leap, back by a step or a third.
      if (
        Math.abs(prevIv) >= 3 &&
        !newPhrase &&
        (Math.sign(iv) === Math.sign(prevIv) || Math.abs(iv) > 2)
      )
        return false;
      // Two skips one way only through one chord.
      if (Math.abs(prevIv) >= 2 && Math.abs(iv) >= 2 && Math.sign(iv) === Math.sign(prevIv)) {
        if (ps.chord !== s.chord || slots[i - 2]!.chord !== s.chord) return false;
        if (i >= 3) {
          const ppp = chosen[i - 3]!;
          if (Math.abs(pp - ppp) >= 2 && Math.sign(pp - ppp) === Math.sign(iv)) return false;
        }
      }
    }
    // The leading tone rises to the tonic (in minor always; in major into I).
    if (mod7(p) === 6 && (raised(k, ps.chord, p) || (s.chord === 'I' && ps.chord === 'V')))
      if (iv !== 1) return false;
    // The cadence: by step to the tonic (or from the dominant, from F5).
    if (s.final) {
      const fromDominant = level.extended && mod7(p) === 4 && Math.abs(iv) <= 4;
      if (Math.abs(iv) !== 1 && !fromDominant) return false;
    }
    // Parallel fifths and octaves with the bass.
    if (s.bass !== null) {
      const j = lastWithBass(i);
      if (j >= 0) {
        const before = slots[j]!.bass!;
        const ic = (((m - s.bass) % 12) + 12) % 12;
        const icBefore = (((midis[j]! - before) % 12) + 12) % 12;
        const moved = m !== midis[j] && s.bass !== before;
        const same = Math.sign(m - midis[j]!) === Math.sign(s.bass - before);
        if (moved && same && ic === icBefore && (ic === 0 || ic === 7)) return false;
      }
    }
    return true;
  }

  function weight(i: number, d: number): number {
    const s = slots[i]!;
    let w = 1;
    const c = ctx.contour[s.phrase]!;
    const firstOfPhrase = slots.findIndex((x) => x.phrase === s.phrase);
    const start = i === firstOfPhrase ? d : chosen[firstOfPhrase]!;
    const t = target(c, start, s.at);
    w *= 0.15 + Math.exp(-((d - t) ** 2) / (2 * 1.1 ** 2));
    if (i > 0 && !s.tied) {
      const p = chosen[i - 1]!;
      const iv = d - p;
      w *= INTERVAL_WEIGHT[Math.min(7, Math.abs(iv))]!;
      if (i >= 2) {
        const prevIv = p - chosen[i - 2]!;
        // A skip turned back by step; a step going on the same way (a line has a direction).
        if (Math.abs(prevIv) >= 2 && Math.abs(iv) === 1 && Math.sign(iv) !== Math.sign(prevIv))
          w *= 1.6;
        if (Math.abs(prevIv) === 1 && Math.abs(iv) === 1)
          w *= Math.sign(iv) === Math.sign(prevIv) ? 1.6 : 0.5;
        // Not zigzagging: a turn right after a turn.
        if (i >= 3) {
          const before = chosen[i - 2]! - chosen[i - 3]!;
          if (iv * prevIv < 0 && prevIv * before < 0) w *= 0.35;
        }
        if (i >= 3 && d === chosen[i - 2] && p === chosen[i - 3]) w *= 0.15;
      }
      if (!isChordTone(s.chord, d)) w *= 0.8;
    }
    if (i === 0) w *= mod7(d) === 0 ? 2 : mod7(d) === 2 ? 1.5 : 0.9;
    const next = slots[i + 1];
    if (next?.final) w *= mod7(d) === 1 ? 2.5 : mod7(d) === 6 ? 1.8 : mod7(d) === 4 ? 0.5 : 1;
    if (s.last && !s.final) w *= mod7(d) === 1 ? 2 : mod7(d) === 4 ? 1.5 : 0.6;
    const uses = chosen.filter((x, j) => x === d && slots[j]!.phrase === s.phrase).length;
    if (uses >= 3) w *= 0.65 ** (uses - 2);
    return w;
  }

  /** At the end of a phrase: it must use its position, not circle round three notes. */
  function phraseOk(phrase: number): boolean {
    const notes = chosen.filter((_, j) => slots[j]!.phrase === phrase);
    const distinct = new Set(notes).size;
    const span = Math.max(...notes) - Math.min(...notes);
    const wanted = notes.length >= 8 ? 4 : notes.length >= 5 ? 3 : 2;
    return distinct >= wanted && span >= Math.min(3, wanted);
  }

  function search(i: number): boolean {
    if (ctx.budget-- <= 0) return false;
    if (i === slots.length) return true;
    const s = slots[i]!;
    const forced = fixed.get(i);
    let candidates: number[];
    if (forced !== undefined) candidates = allowed(i, forced) ? [forced] : [];
    else if (s.tied) candidates = allowed(i, chosen[i - 1]!) ? [chosen[i - 1]!] : [];
    else {
      const w = windows[s.phrase]!;
      const options: [number, number][] = [];
      for (let d = w.lo; d <= w.hi; d++) if (allowed(i, d)) options.push([d, weight(i, d)]);
      candidates = [];
      while (options.length > 0) {
        const d = pick(ctx.rng, options);
        candidates.push(d);
        options.splice(
          options.findIndex(([x]) => x === d),
          1,
        );
      }
    }
    for (const d of candidates) {
      chosen[i] = d;
      midis[i] = midiOfSlot(i, d);
      if (s.last && !phraseOk(s.phrase)) continue;
      if (search(i + 1)) return true;
      if (ctx.budget <= 0) return false;
    }
    chosen.length = i;
    midis.length = i;
    return false;
  }

  return search(0) ? chosen.slice() : null;
}

// --- Assembling a fragment -------------------------------------------------------------------

const BUDGET = 4000;
const MAX_ATTEMPTS = 200;

/** Which hand plays each bar of a line passed between the hands (F3). */
function turns(bars: number, rng: Rng): Hand[] {
  const patterns: (readonly [Hand[], number])[] = [
    [['right', 'left', 'right', 'left'], 3],
    [['right', 'left', 'right', 'right'], 2],
    [['right', 'right', 'left', 'left'], 1.5],
    [['left', 'right', 'left', 'right'], 1.5],
    [['right', 'left', 'left', 'right'], 1],
    [['left', 'left', 'right', 'right'], 1],
  ];
  return pick(rng, patterns).slice(0, bars);
}

function slotsOf(
  plan: Plan,
  rhythm: readonly string[][],
  harmony: readonly BarHarmony[],
  left: readonly LeftEvent[],
  leftMidi: (e: LeftEvent, degree: number) => number,
): { slots: Slot[]; beats: (Beat & { bar: number })[] } {
  const bar = barTicks(plan.meter);
  const beats = rhythm.flatMap((cells, b) =>
    beatsOfCells(cells).map((beat) => ({ ...beat, bar: b })),
  );
  const notes = beats.filter((x) => !x.rest);
  const phraseOf = (b: number) => plan.phrases.findLastIndex((p) => p <= b);
  const phraseSpan = (p: number) => {
    const from = plan.phrases[p]! * bar;
    const to = (plan.phrases[p + 1] ?? plan.bars) * bar;
    return [from, to] as const;
  };
  const slots = notes.map((x, i): Slot => {
    const onset = x.bar * bar + x.start;
    const beat = x.start / TICKS_PER_QUARTER;
    const slotsOfBar = harmony[x.bar]!;
    const phrase = phraseOf(x.bar);
    const [from, to] = phraseSpan(phrase);
    const sounding = left.filter((e) => {
      const at = e.bar * bar + e.start;
      return e.degrees.length > 0 && at < onset + x.ticks && at + e.ticks > onset;
    });
    const struck = left.filter((e) => e.bar * bar + e.start === onset && e.degrees.length > 0);
    const bassEvent = struck[0];
    return {
      bar: x.bar,
      onset,
      ticks: x.ticks,
      strong:
        beat === 0 ||
        (plan.meter === '4/4' && beat === 2) ||
        slotsOfBar.some((s) => s.beat === beat) ||
        x.ticks >= 2 * TICKS_PER_QUARTER,
      chord: chordAt(slotsOfBar, beat),
      tied: x.tied,
      phrase,
      first: phraseOf(notes[i - 1]?.bar ?? -1) !== phrase,
      last: i === notes.length - 1 || phraseOf(notes[i + 1]!.bar) !== phrase,
      final: i === notes.length - 1,
      at: (onset - from) / Math.max(1, to - from - bar),
      cell: x.cell,
      under: Math.max(-1, ...sounding.flatMap((e) => e.degrees.map((d) => leftMidi(e, d)))),
      struck: struck.flatMap((e) =>
        e.degrees.map((d) => ({ midi: leftMidi(e, d), passing: e.passing === true })),
      ),
      // A note held on by a tie is not struck with the bass: no pair for parallels.
      bass: bassEvent && !x.tied ? leftMidi(bassEvent, bassEvent.degrees[0]!) : null,
    };
  });
  return { slots, beats };
}

/** The finger of a note in a five-finger position whose thumb (right hand) or fifth finger (left) is at `base`. */
function fingerAt(hand: Hand, degree: number, base: number): number {
  const offset = degree - base;
  return Math.min(5, Math.max(1, hand === 'right' ? offset + 1 : 5 - offset));
}

/**
 * The left hand's finger for a note of a chord shape (a dyad or a triad, played together or
 * broken): 5 on the lowest note, 1 on the highest, 3 on a middle note a third above the lowest,
 * else 2.
 */
function shapeFinger(shape: readonly number[], degree: number): number {
  const low = Math.min(...shape);
  const high = Math.max(...shape);
  if (degree === low) return 5;
  if (degree === high) return 1;
  return degree - low <= 2 ? 3 : 2;
}

/**
 * Where the hand is for its first phrase: the five-finger position (within a stretched one, the
 * five notes holding most of the phrase's) whose lowest note is `base`.
 */
function positionBase(degrees: readonly number[], lo: number, hi: number): number {
  let best = lo;
  let most = -1;
  for (let base = lo; base + 4 <= Math.max(hi, lo + 4); base++) {
    const inside = degrees.filter((d) => d >= base && d <= base + 4).length;
    if (inside > most) {
      most = inside;
      best = base;
    }
  }
  return best;
}

/** Raises some lower neighbours a whole step below their note (F7-F8), at most two. */
function chromaticNeighbours(
  melody: { degree: number; pitch: SpelledPitch; midi: number; slot: Slot; alter: number }[],
  crossed: (slot: Slot, pitch: SpelledPitch) => boolean,
  minor: boolean,
  rng: Rng,
): void {
  let count = 0;
  for (let i = 1; i + 1 < melody.length && count < 2; i++) {
    const [a, n, b] = [melody[i - 1]!, melody[i]!, melody[i + 1]!];
    if (a.degree !== b.degree || n.degree !== a.degree - 1 || n.slot.tied || b.slot.tied) continue;
    if (n.slot.strong || n.slot.ticks > TICKS_PER_QUARTER) continue;
    if (a.midi - n.midi !== 2) continue;
    // Leading to the dominant, and to the supertonic, mediant or submediant in major (to the
    // subdominant in minor): the chromatic notes of the common styles.
    if (!(minor ? [3, 4] : [1, 2, 4, 5]).includes(mod7(a.degree))) continue;
    // A sharp on a black key, or a natural for a flat: never B♯, E♯ or a double sharp.
    const up = { ...n.pitch, alter: n.pitch.alter + 1 };
    if (!(n.pitch.alter === -1 || (n.pitch.alter === 0 && isBlack(midiOf(up))))) continue;
    // Not against the same letter in the left hand in the bar (a false relation).
    if (crossed(n.slot, up)) continue;
    // Not into a fifth or an octave with the bass struck with it (it could move in parallel).
    const bass = n.slot.bass;
    if (bass !== null && [0, 7].includes((((n.midi + 1 - bass) % 12) + 12) % 12)) continue;
    if (!chance(rng, 0.5)) continue;
    n.alter = 1;
    count++;
  }
}

/**
 * The fragment of `level` for `seed`, as generator `version` makes it. Throws for a version this
 * build cannot make (`SIGHT_GENERATOR_VERSIONS`).
 */
export function generateFragment(
  levelId: SightLevelId,
  seed: number,
  version = SIGHT_GENERATOR_VERSION,
): SightFragment {
  if (!SIGHT_GENERATOR_VERSIONS.includes(version))
    throw new RangeError(`sight-reading generator version ${version} is not known`);
  const level = getSightLevel(levelId);
  const rng = seededRng(seed);
  const k = pick(
    rng,
    level.keys.map((x) => [x, 1] as const),
  );
  const meter = pick(rng, level.meters);
  const bars = level.bars;
  const plan: Plan = {
    meter,
    bars,
    phrases: bars === 8 ? [0, 4] : [0],
    parallel: bars === 8 && chance(rng, 0.55),
  };
  const spell = speller(k, level.texture);
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const fragment = attemptFragment(level, plan, k, spell, rng);
    if (fragment)
      return {
        level: levelId,
        seed,
        version,
        key: k,
        fifths: keySignature(k.mode === 'major' ? 'major' : 'naturalMinor', k.tonic).fifths,
        meter,
        bars,
        ...fragment,
        phrases: plan.phrases,
        attempts: attempt,
      };
  }
  throw new Error(`no sight-reading fragment for ${levelId}:${seed}`);
}

function attemptFragment(
  level: SightLevel,
  plan: Plan,
  k: SightKey,
  spell: Speller,
  rng: Rng,
): Pick<SightFragment, 'notes' | 'harmony'> | null {
  const { meter, bars } = plan;
  const harmony = harmonyPlan(level, plan, k.mode, rng);
  const rhythm = melodyRhythm(level, plan, rng);
  const left = leftBars(level, plan, harmony, k, spell, rng);
  if (!left) return null;
  const leftMidi = (e: LeftEvent, d: number) => spell.midi('left', d, e.chord);
  const { slots } = slotsOf(plan, rhythm, harmony, left, leftMidi);
  const hands: Hand[] =
    level.texture === 'left'
      ? Array.from({ length: bars }, () => 'left')
      : level.texture === 'turns'
        ? turns(bars, rng)
        : Array.from({ length: bars }, () => 'right');
  const windows = positions(level, plan, spell, rng);
  const contour = plan.phrases.map((_, p) =>
    contourOf(windows[p]!, p === plan.phrases.length - 1 ? 'full' : 'half', rng),
  );
  const ctx: MelodyContext = {
    level,
    plan,
    k,
    spell,
    hands,
    windows,
    slots,
    contour,
    rng,
    budget: BUDGET,
  };
  // A parallel period repeats bars 1-2 in bars 5-6 (an octave up when the hand moved an octave).
  let degrees = solveMelody(ctx, new Map());
  if (!degrees) return null;
  if (plan.parallel && chance(rng, 0.6)) {
    const shift = windows[1]!.lo - windows[0]!.lo;
    if (shift === 0 || shift === 7) {
      // The first phrase as it is, bars 5-6 as bars 1-2; the rest is walked again.
      const fixed = new Map<number, number>();
      slots.forEach((s, i) => {
        if (s.bar < 4) fixed.set(i, degrees![i]!);
        else if (s.bar === 4 || s.bar === 5) {
          const from = slots.findIndex((x) => x.onset === s.onset - 4 * barTicks(meter));
          if (from >= 0) fixed.set(i, degrees![from]! + shift);
        }
      });
      ctx.budget = BUDGET;
      const again = solveMelody(ctx, fixed);
      if (again) degrees = again;
    }
  }

  const melody = slots.map((slot, i) => {
    const hand = hands[slot.bar]!;
    const degree = degrees[i]!;
    const pitch = spell.pitch(hand, degree, slot.chord);
    return { slot, degree, pitch, midi: midiOf(pitch), alter: 0 };
  });
  if (level.chromatic) {
    const crossed = (slot: Slot, pitch: SpelledPitch) =>
      left.some(
        (e) =>
          e.bar === slot.bar &&
          e.degrees.some((d) => {
            const lp = spell.pitch('left', d, e.chord);
            return lp.step === pitch.step && lp.alter !== pitch.alter;
          }),
      );
    chromaticNeighbours(melody, crossed, k.mode === 'minor', rng);
  }

  // The notes.
  const bar = barTicks(meter);
  const notes: SightNote[] = [];
  melody.forEach(({ slot, degree, alter }, i) => {
    const hand = hands[slot.bar]!;
    const base = spell.pitch(hand, degree, slot.chord);
    const pitch = alter ? { ...base, alter: base.alter + alter } : base;
    notes.push({
      hand,
      pitch,
      midi: midiOf(pitch),
      onset: slot.onset,
      duration: slot.ticks,
      tieStart: melody[i + 1]?.slot.tied === true,
      tieStop: slot.tied,
      finger: null,
      cell: slot.cell,
    });
  });
  for (const e of left) {
    for (const d of e.degrees) {
      const pitch = spell.pitch('left', d, e.chord);
      notes.push({
        hand: 'left',
        pitch,
        midi: midiOf(pitch),
        onset: e.bar * bar + e.start,
        duration: e.ticks,
        tieStart: false,
        tieStop: false,
        finger: null,
        cell: e.cell,
      });
    }
  }
  // The last bar's note in 3/4 is the final note (a dotted half before R3).
  for (const n of notes) if (n.cell === FINAL) n.cell = 'hd';
  notes.sort(
    (a, b) =>
      a.onset - b.onset || (a.hand === b.hand ? 0 : a.hand === 'left' ? -1 : 1) || a.midi - b.midi,
  );

  // Fingering: each hand's first note or chord, from where the hand lies for its first phrase.
  for (const hand of ['right', 'left'] as const) {
    const own = notes.filter((n) => n.hand === hand);
    if (own.length === 0) continue;
    const firstOnset = own[0]!.onset;
    const phraseEnd = plan.phrases[1] !== undefined ? plan.phrases[1] * bar : Infinity;
    let degreesOf: number[];
    let lo: number;
    let hi: number;
    if (hand === 'left' && level.texture !== 'left' && level.texture !== 'turns') {
      degreesOf = left.filter((e) => e.bar * bar + e.start < phraseEnd).flatMap((e) => e.degrees);
      [lo, hi] = leftWindow(level);
    } else {
      degreesOf = melody
        .filter((m) => hands[m.slot.bar] === hand && m.slot.onset < phraseEnd)
        .map((m) => m.degree);
      const w = windows[0]!;
      [lo, hi] = [w.lo, w.hi];
    }
    const lowest = Math.min(lo, ...degreesOf);
    const highest = Math.max(hi, ...degreesOf);
    const firstNotes = own.filter((n) => n.onset === firstOnset);
    const degreeOf = (n: SightNote) => {
      if (hand === 'left' && level.texture !== 'left' && level.texture !== 'turns') {
        const e = left.find((x) => x.bar * bar + x.start === n.onset)!;
        return e.degrees[firstNotes.indexOf(n)]!;
      }
      return melody.find((m) => m.slot.onset === n.onset && hands[m.slot.bar] === hand)!.degree;
    };
    const first = firstNotes.map(degreeOf);
    // A phrase starting on its lowest note starts on the thumb (the fifth finger in the left
    // hand); one starting on its highest, the other way round.
    const base =
      first[0] === Math.min(...degreesOf)
        ? first[0]
        : first[0] === Math.max(...degreesOf)
          ? first[0] - 4
          : positionBase(degreesOf, lowest, highest);
    const chordShape =
      hand === 'left' && level.texture === 'chords'
        ? TRIADS[left.find((e) => e.bar * bar + e.start === firstOnset)!.chord]
        : first.length > 1
          ? first
          : null;
    firstNotes.forEach((n, i) => {
      n.finger = chordShape ? shapeFinger(chordShape, first[i]!) : fingerAt(hand, first[i]!, base);
    });
  }
  return { notes, harmony };
}
