# Hanon, The Virtuoso Pianist (Schirmer [1900], IMSLP #91547): Nos. 42 and 43, reader s7B
X = []
X.append(dict(
    number=42,
    part='C',
    pdf=70,
    page=69,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'C3 Eb3 F#3 A3 C4 A3 F#3 Eb3', 'lh': 'C2 Eb2 F#2 A2 C3 A2 F#2 Eb2', 'marks': '"Repeat this measure 4 times." printed over it; end-repeat sign'},
        {'rh': 'C3 Eb3 F#3 A3 C4 Eb4 F#4 A4', 'lh': 'C2 Eb2 F#2 A2 C3 Eb3 F#3 A3', 'marks': 'start-repeat sign; RH steps 4-7 on the upper staff, LH on the lower staff'},
        {'rh': 'C5 Eb5 F#5 A5 C6 A5 F#5 Eb5', 'lh': 'C4 Eb4 F#4 A4 C5 A4 F#4 Eb4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'C5 A4 F#4 Eb4 C4 A3 F#3 Eb3', 'lh': 'C4 A3 F#3 Eb3 C3 A2 F#2 Eb2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'RH', 5, '4'),
        (1, 'RH', 6, '3'),
        (1, 'RH', 7, '2'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 1, '2'),
        (2, 'RH', 2, '3'),
        (2, 'RH', 3, '4'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 1, '4'),
        (2, 'LH', 2, '3'),
        (2, 'LH', 3, '2'),
        (2, 'LH', 4, '1'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='Heading: "Extension (stretching) of the fingers in chords of the diminished seventh, in arpeggios." M.M. quarter = 60 to 120. Each section: one stretching bar ("Repeat this measure 4 times." on the first, "4 times." on the others) closed by an end-repeat, then three arpeggio bars between repeat signs. Every bar is 8 sixteenths per hand = 2/4. Section C (C Eb F# A) is the only one with fuller fingering: stretch bar RH 1 2 3 4 5 4 3 2; bar 2 RH 1 2 3 4 on steps 0-3 (no digit on step 4) and LH 5 4 3 2 1 4; bar 3 LH only 4 (no 1 on step 4). Both hands of the stretch bar are on the bass staff. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='D',
    pdf=70,
    page=69,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'D3 F3 Ab3 B3 D4 B3 Ab3 F3', 'lh': 'D2 F2 Ab2 B2 D3 B2 Ab2 F2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'D3 F3 Ab3 B3 D4 F4 Ab4 B4', 'lh': 'D2 F2 Ab2 B2 D3 F3 Ab3 B3', 'marks': 'start-repeat sign'},
        {'rh': 'D5 F5 Ab5 B5 D6 B5 Ab5 F5', 'lh': 'D4 F4 Ab4 B4 D5 B4 Ab4 F4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'D5 B4 Ab4 F4 D4 B3 Ab3 F3', 'lh': 'D4 B3 Ab3 F3 D3 B2 Ab2 F2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='D F Ab B. Stretch bar both hands on the bass staff. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='E',
    pdf=70,
    page=69,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'E3 G3 Bb3 C#4 E4 C#4 Bb3 G3', 'lh': 'E2 G2 Bb2 C#3 E3 C#3 Bb2 G2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'E3 G3 Bb3 C#4 E4 G4 Bb4 C#5', 'lh': 'E2 G2 Bb2 C#3 E3 G3 Bb3 C#4', 'marks': 'start-repeat sign'},
        {'rh': 'E5 G5 Bb5 C#6 E6 C#6 Bb5 G5', 'lh': 'E4 G4 Bb4 C#5 E5 C#5 Bb4 G4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'E5 C#5 Bb4 G4 E4 C#4 Bb3 G3', 'lh': 'E4 C#4 Bb3 G3 E3 C#3 Bb2 G2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='E G Bb C#. Bar 3: LH has only the 4 on step 1 (no 1 on step 4). Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='F',
    pdf=70,
    page=69,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'F3 Ab3 B3 D4 F4 D4 B3 Ab3', 'lh': 'F2 Ab2 B2 D3 F3 D3 B2 Ab2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'F3 Ab3 B3 D4 F4 Ab4 B4 D5', 'lh': 'F2 Ab2 B2 D3 F3 Ab3 B3 D4', 'marks': 'start-repeat sign'},
        {'rh': 'F5 Ab5 B5 D6 F6 D6 B5 Ab5', 'lh': 'F4 Ab4 B4 D5 F5 D5 B4 Ab4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'F5 D5 B4 Ab4 F4 D4 B3 Ab3', 'lh': 'F4 D4 B3 Ab3 F3 D3 B2 Ab2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=['bar 4 LH step 0: the digit is broken in the 600-dpi scan (only a fragment left); the 300-dpi copy (IMSLP00875) shows a clear 1'],
    note='F Ab B D. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='G',
    pdf=70,
    page=69,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'G3 Bb3 C#4 E4 G4 E4 C#4 Bb3', 'lh': 'G2 Bb2 C#3 E3 G3 E3 C#3 Bb2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'G3 Bb3 C#4 E4 G4 Bb4 C#5 E5', 'lh': 'G2 Bb2 C#3 E3 G3 Bb3 C#4 E4', 'marks': 'start-repeat sign'},
        {'rh': 'G5 Bb5 C#6 E6 G6 E6 C#6 Bb5', 'lh': 'G4 Bb4 C#5 E5 G5 E5 C#5 Bb4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'G5 E5 C#5 Bb4 G4 E4 C#4 Bb3', 'lh': 'G4 E4 C#4 Bb3 G3 E3 C#3 Bb2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='G Bb C# E. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='A',
    pdf=70,
    page=69,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'A3 C4 Eb4 F#4 A4 F#4 Eb4 C4', 'lh': 'A2 C3 Eb3 F#3 A3 F#3 Eb3 C3', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'A3 C4 Eb4 F#4 A4 C5 Eb5 F#5', 'lh': 'A2 C3 Eb3 F#3 A3 C4 Eb4 F#4', 'marks': 'start-repeat sign'},
        {'rh': 'A5 C6 Eb6 F#6 A6 F#6 Eb6 C6', 'lh': 'A4 C5 Eb5 F#5 A5 F#5 Eb5 C5', 'marks': '8va dashed line over all 8 RH steps (written A4 C5 Eb5 F#5 A5 F#5 Eb5 C5); lower staff changes to treble clef at the start of the bar (LH written A4...)'},
        {'rh': 'A5 F#5 Eb5 C5 A4 F#4 Eb4 C4', 'lh': 'A4 F#4 Eb4 C4 A3 F#3 Eb3 C3', 'marks': 'end-repeat sign; LH steps 0-3 on the lower staff in treble clef, bass clef before LH step 4; no 8va'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=['bar 2 RH: the step-0 "1" is printed between the staves above the A3 head (RH, stem up) and the step-4 "1" is printed just under the A4 head, below the beam, rather than above the beam; read both as RH digits'],
    note='A C Eb F#. Bar 3: LH has only the 4 on step 1. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='B',
    pdf=71,
    page=70,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'B3 D4 F4 Ab4 B4 Ab4 F4 D4', 'lh': 'B2 D3 F3 Ab3 B3 Ab3 F3 D3', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'B3 D4 F4 Ab4 B4 D5 F5 Ab5', 'lh': 'B2 D3 F3 Ab3 B3 D4 F4 Ab4', 'marks': 'start-repeat sign; LH steps 5-7 (D4 F4 Ab4) written on the upper (treble) staff'},
        {'rh': 'B5 D6 F6 Ab6 B6 Ab6 F6 D6', 'lh': 'B4 D5 F5 Ab5 B5 Ab5 F5 D5', 'marks': '8va dashed line over all 8 RH steps (written B4 D5 F5 Ab5 B5 Ab5 F5 D5); lower staff changes to treble clef at the start of the bar'},
        {'rh': 'B5 Ab5 F5 D5 B4 Ab4 F4 D4', 'lh': 'B4 Ab4 F4 D4 B3 Ab3 F3 D3', 'marks': 'end-repeat sign; LH steps 0-3 in treble clef on the lower staff, bass clef before LH step 4'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='B D F Ab. Bar 2 LH Ab4 has no flat of its own; the RH Ab4 flat earlier in the bar on the same (treble) staff position applies. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=42,
    part='close',
    pdf=71,
    page=70,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'B4 Ab4 F4 D4 B3 Ab3 F3 D3', 'lh': 'B3 Ab3 F3 D3 B2 Ab2 F2 D2', 'marks': 'after the end-repeat of section B, no repeat signs; RH steps 4-7 written on the lower (bass) staff; thin double bar at the end'},
        {'rh': 'C3', 'lh': 'C2', 'marks': 'both steps half notes, both on the lower (bass) staff: C3 stem up, C2 stem down (ledger); upper staff empty (no rest printed); final double bar'},
    ],
    digits=[
        (1, 'RH', 1, '4'),
        (1, 'RH', 5, '4'),
        (1, 'LH', 0, '1'),
        (1, 'LH', 4, '1'),
    ],
    uncertain=['bar 2: nothing on the upper staff; the two half notes share the bass staff with opposite stems, so C3 (stem up) is given to RH and C2 (stem down) to LH - the hand split is inferred from stem direction only'],
    note='Two closing bars after the last section. Bar 1 is 8 sixteenths per hand; bar 2 is one half note per hand (2/4). Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='C',
    pdf=71,
    page=70,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'C3 E3 G3 Bb3 C4 Bb3 G3 E3', 'lh': 'C2 E2 G2 Bb2 C3 Bb2 G2 E2', 'marks': '"Repeat this measure 4 times." printed over it; end-repeat sign'},
        {'rh': 'C3 E3 G3 Bb3 C4 E4 G4 Bb4', 'lh': 'C2 E2 G2 Bb2 C3 E3 G3 Bb3', 'marks': 'start-repeat sign'},
        {'rh': 'C5 E5 G5 Bb5 C6 Bb5 G5 E5', 'lh': 'C4 E4 G4 Bb4 C5 Bb4 G4 E4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'C5 Bb4 G4 E4 C4 Bb3 G3 E3', 'lh': 'C4 Bb3 G3 E3 C3 Bb2 G2 E2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='Heading: "Extension of the fingers in chords of the dominant seventh, in arpeggios." M.M. quarter = 60 to 120. Each section: one stretching bar ("Repeat this measure 4 times." on the first, "4 times." on the others) closed by an end-repeat, then three arpeggio bars between repeat signs. Every bar is 8 sixteenths per hand = 2/4. C E G Bb. Both hands of the stretch bar on the bass staff. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='D',
    pdf=71,
    page=70,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'D3 F#3 A3 C4 D4 C4 A3 F#3', 'lh': 'D2 F#2 A2 C3 D3 C3 A2 F#2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'D3 F#3 A3 C4 D4 F#4 A4 C5', 'lh': 'D2 F#2 A2 C3 D3 F#3 A3 C4', 'marks': 'start-repeat sign'},
        {'rh': 'D5 F#5 A5 C6 D6 C6 A5 F#5', 'lh': 'D4 F#4 A4 C5 D5 C5 A4 F#4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'D5 C5 A4 F#4 D4 C4 A3 F#3', 'lh': 'D4 C4 A3 F#3 D3 C3 A2 F#2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='D F# A C. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='E',
    pdf=71,
    page=70,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'E3 G#3 B3 D4 E4 D4 B3 G#3', 'lh': 'E2 G#2 B2 D3 E3 D3 B2 G#2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'E3 G#3 B3 D4 E4 G#4 B4 D5', 'lh': 'E2 G#2 B2 D3 E3 G#3 B3 D4', 'marks': 'start-repeat sign'},
        {'rh': 'E5 G#5 B5 D6 E6 D6 B5 G#5', 'lh': 'E4 G#4 B4 D5 E5 D5 B4 G#4', 'marks': 'LH written on the upper (treble) staff'},
        {'rh': 'E5 D5 B4 G#4 E4 D4 B3 G#3', 'lh': 'E4 D4 B3 G#3 E3 D3 B2 G#2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='E G# B D. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='F',
    pdf=72,
    page=71,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'F3 A3 C4 Eb4 F4 Eb4 C4 A3', 'lh': 'F2 A2 C3 Eb3 F3 Eb3 C3 A2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'F3 A3 C4 Eb4 F4 A4 C5 Eb5', 'lh': 'F2 A2 C3 Eb3 F3 A3 C4 Eb4', 'marks': 'start-repeat sign'},
        {'rh': 'F5 A5 C6 Eb6 F6 Eb6 C6 A5', 'lh': 'F4 A4 C5 Eb5 F5 Eb5 C5 A4', 'marks': 'LH written on the upper (treble) staff; no 8va (ledger lines)'},
        {'rh': 'F5 Eb5 C5 A4 F4 Eb4 C4 A3', 'lh': 'F4 Eb4 C4 A3 F3 Eb3 C3 A2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (3, 'LH', 4, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='F A C Eb. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='G',
    pdf=72,
    page=71,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'G3 B3 D4 F4 G4 F4 D4 B3', 'lh': 'G2 B2 D3 F3 G3 F3 D3 B2', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'G3 B3 D4 F4 G4 B4 D5 F5', 'lh': 'G2 B2 D3 F3 G3 B3 D4 F4', 'marks': 'start-repeat sign'},
        {'rh': 'G5 B5 D6 F6 G6 F6 D6 B5', 'lh': 'G4 B4 D5 F5 G5 F5 D5 B4', 'marks': 'LH written on the upper (treble) staff; no 8va (ledger lines up to G6)'},
        {'rh': 'G5 F5 D5 B4 G4 F4 D4 B3', 'lh': 'G4 F4 D4 B3 G3 F3 D3 B2', 'marks': 'end-repeat sign'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (4, 'RH', 0, '1'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=['bar 2 LH step 5: the 4 is printed above the B3 head (between the staves), not below the beam as elsewhere; read as LH'],
    note='G B D F (no accidentals). Bar 3: LH only the 4 on step 1. Bar 4: an extra RH 1 on step 0, printed only in this section.',
))
X.append(dict(
    number=43,
    part='A',
    pdf=72,
    page=71,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'A3 C#4 E4 G4 A4 G4 E4 C#4', 'lh': 'A2 C#3 E3 G3 A3 G3 E3 C#3', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'A3 C#4 E4 G4 A4 C#5 E5 G5', 'lh': 'A2 C#3 E3 G3 A3 C#4 E4 G4', 'marks': 'start-repeat sign; lower staff changes to treble clef before LH step 6 (E4)'},
        {'rh': 'A5 C#6 E6 G6 A6 G6 E6 C#6', 'lh': 'A4 C#5 E5 G5 A5 G5 E5 C#5', 'marks': '8va dashed line over all 8 RH steps (written A4 C#5 E5 G5 A5 G5 E5 C#5); LH on the lower staff in treble clef'},
        {'rh': 'A5 G5 E5 C#5 A4 G4 E4 C#4', 'lh': 'A4 G4 E4 C#4 A3 G3 E3 C#3', 'marks': 'end-repeat sign; LH steps 0-3 in treble clef, bass clef before LH step 4; no 8va'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=['bar 4 LH step 4: the 1 is printed above the A3 head (just after the bass clef), not below the beam; read as LH'],
    note='A C# E G. Stretch bar RH wholly on the treble staff. Bar 3: LH only the 4 on step 1. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='B',
    pdf=72,
    page=71,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'B3 D#4 F#4 A4 B4 A4 F#4 D#4', 'lh': 'B2 D#3 F#3 A3 B3 A3 F#3 D#3', 'marks': 'start-repeat sign; "4 times." printed over it; end-repeat sign'},
        {'rh': 'B3 D#4 F#4 A4 B4 D#5 F#5 A5', 'lh': 'B2 D#3 F#3 A3 B3 D#4 F#4 A4', 'marks': 'start-repeat sign; lower staff changes to treble clef before LH step 6 (F#4)'},
        {'rh': 'B5 D#6 F#6 A6 B6 A6 F#6 D#6', 'lh': 'B4 D#5 F#5 A5 B5 A5 F#5 D#5', 'marks': '8va dashed line over all 8 RH steps (written B4 D#5 F#5 A5 B5 A5 F#5 D#5); LH on the lower staff in treble clef'},
        {'rh': 'B5 A5 F#5 D#5 B4 A4 F#4 D#4', 'lh': 'B4 A4 F#4 D#4 B3 A3 F#3 D#3', 'marks': 'end-repeat sign; LH steps 0-3 in treble clef, bass clef before LH step 4; no 8va'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '5'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (2, 'RH', 0, '1'),
        (2, 'RH', 4, '1'),
        (2, 'LH', 0, '5'),
        (2, 'LH', 5, '4'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 1, '4'),
        (4, 'RH', 1, '4'),
        (4, 'RH', 5, '4'),
        (4, 'LH', 0, '1'),
        (4, 'LH', 4, '1'),
    ],
    uncertain=[],
    note='B D# F# A. Stretch bar RH wholly on the treble staff. Bar 3: LH only the 4 on step 1. Accidentals: where a note has no sign of its own, the accidental printed earlier in the same bar on the same staff position (often in the other hand) is taken as applying.',
))
X.append(dict(
    number=43,
    part='close',
    pdf=72,
    page=71,
    time='2/4',
    unit='sixteenths',
    bars=[
        {'rh': 'C4 E4 G4 B4 C5 E5 G5 B5', 'lh': 'C3 E3 G3 B3 C4 E4 G4 B4', 'marks': 'no repeat signs; LH steps 4-7 written on the upper (treble) staff'},
        {'rh': 'C6 B5 G5 E5 C5 B4 G4 E4', 'lh': 'C5 B4 G4 E4 C4 B3 G3 E3', 'marks': 'LH steps 0-3 on the upper staff, 4-7 on the bass staff'},
        {'rh': 'C4 E4 G4 B4 C5 B4 G4 E4', 'lh': 'C3 E3 G3 B3 C4 B3 G3 E3', 'marks': ''},
        {'rh': 'C4 B3 G3 E3 C3 E3 G3 B3', 'lh': 'C3 B2 G2 E2 C2 E2 G2 B2', 'marks': 'RH written on the lower (bass) staff; upper staff empty'},
        {'rh': 'E3+G3+C4', 'lh': 'C2+E2+G2+C3', 'marks': 'final chord, half notes, all on the bass staff: upper stem (RH) through C4 G3 E3, lower stem (LH) through C3 G2 E2 C2; final double bar'},
    ],
    digits=[
        (1, 'RH', 0, '1'),
        (1, 'RH', 1, '2'),
        (1, 'RH', 2, '3'),
        (1, 'RH', 3, '4'),
        (1, 'RH', 4, '1'),
        (1, 'LH', 0, '5'),
        (1, 'LH', 1, '4'),
        (1, 'LH', 2, '3'),
        (1, 'LH', 3, '2'),
        (1, 'LH', 4, '1'),
        (1, 'LH', 5, '4'),
        (2, 'RH', 0, '5'),
        (2, 'RH', 5, '4'),
        (2, 'LH', 4, '1'),
        (3, 'RH', 0, '1'),
        (3, 'RH', 4, '5'),
        (3, 'LH', 0, '5'),
        (4, 'RH', 1, '4'),
        (4, 'LH', 0, '1'),
        (5, 'RH', 0, '125'),
    ],
    uncertain=['bar 5: seven hollow heads stacked on one bass staff (C2 E2 G2 C3 E3 G3 C4); split by stems at 1200 dpi: the up-stem runs from C4 down to E3, the down-stem from C2 up to C3; the digits 5 2 1 stand beside C4 G3 E3. So RH E3+G3+C4 (1 2 5), LH C2+E2+G2+C3 with no digits', 'bar 2 LH step 4: the 1 is printed above the C4 head (ledger, bass staff), not below the beam'],
    note='Five closing bars after section B, ending on C. The Bs are B natural throughout (no flat anywhere in these bars): the close arpeggiates C E G B, not the C dominant seventh. Bars 1-4 are 8 sixteenths per hand, bar 5 one half-note chord per hand (2/4). Printed under it: "End of Part II." and "Parts I and II of this work being the key to the difficulties in Part III, it is evidently very important that they should be thoroughly mastered before commencing the virtuoso studies contained in Part III."',
))
